import type { DslDiagnosticPresentation } from "@nuinuicad/nui-language";
import type { CompilerDiagnostic, CompilerDiagnosticRelatedInformation } from "./compilerDiagnostics";
import { createTranslator, resolveLocale, type TranslationCatalog } from "./localization";

/**
 * Problems presentation is intentionally a VS Code-owned concern.  The DSL
 * and runtime layers only carry the stable key and primitive parameters; this
 * catalog is the only place where those identities become user-facing text.
 */
export const diagnosticTranslationCatalog = {
  "typoSuggestion.diagnosticSuffix": { en: "Did you mean '{candidate}'?", ja: "「{candidate}」のことですか？" },
  "diagnostic.related.first-export": { en: "First export with this name", ja: "この名前の最初のexport" },
  "diagnostic.missing-attribute-value": { en: "Argument '{parameter}' has no value.", ja: "引数「{parameter}」の値がありません。" },
  "diagnostic.unknown-dsl-keyword": { en: "Unknown DSL keyword.", ja: "不明なDSLキーワードです。" },
  "diagnostic.unknown-type": { en: "Unknown type annotation '{type}'.", ja: "不明な型注釈です: {type}" },
  "diagnostic.unknown-construction": { en: "Category '{category}' has no construction '{construction}'. Candidates: {candidates}.", ja: "category「{category}」にconstruction「{construction}」はありません。候補: {candidates}。" },
  "diagnostic.construction-category-mismatch": { en: "Construction '{construction}' does not match category '{category}'. Allowed categories: {categories}. Candidates: {candidates}.", ja: "category「{category}」とconstruction「{construction}」の組み合わせは不一致です。使用できるcategory: {categories}。候補: {candidates}。" },
  "diagnostic.unknown-construction-argument": { en: "Construction '{construction}' has no argument '{argument}'. Candidates: {candidates}.", ja: "construction「{construction}」に引数「{argument}」はありません。候補: {candidates}。" },
  "diagnostic.geometry-reference-type-mismatch": { en: "Reference '{target}' is not a line or curve.", ja: "参照先「{target}」は線・曲線ではありません。" },
  "diagnostic.undefined-geometry-reference": { en: "Geometry reference '{reference}' could not be resolved.", ja: "geometry参照「{reference}」を解決できません。" },
  "diagnostic.invalid-source-reference": { en: "Invalid source reference '{reference}'.", ja: "参照「{reference}」が不正です。" },
  "diagnostic.missing-sigil": { en: "Element-property reference '{reference}' requires '@'.", ja: "要素プロパティ参照「{reference}」には「@」が必要です。" },
  "diagnostic.invalid-choice-literal": { en: "Choice literal '{value}' is not valid for {expected}.", ja: "choice literal「{value}」は{expected}では使用できません。" },
  "diagnostic.invalid-choice-type": { en: "Invalid choice type.", ja: "choice型が不正です。" },
  "diagnostic.duplicate-choice-option": { en: "Choice option '{option}' is duplicated.", ja: "choice option「{option}」が重複しています。" },
  "diagnostic.scalar-type-mismatch": { en: "Type mismatch (expected {expected}, got {actual}).", ja: "型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.function-arity-mismatch": { en: "Function '{name}' has the wrong number of arguments (expected {expected}, got {actual}).", ja: "関数「{name}」の引数の数が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.function-call-style-mismatch": { en: "The function call style is not supported.", ja: "関数の呼び出し形式が不正です。" },
  "diagnostic.duplicate-function-argument": { en: "Function '{name}' has a duplicate argument '{argument}'.", ja: "関数「{name}」の引数「{argument}」が重複しています。" },
  "diagnostic.missing-function-argument": { en: "Required argument '{parameter}' is missing from function '{name}'.", ja: "関数「{name}」に必須引数「{parameter}」がありません。" },
  "diagnostic.unknown-function": { en: "Unknown function '{name}'.", ja: "不明な関数「{name}」です。" },
  "diagnostic.unknown-function-argument": { en: "Function '{name}' has no argument '{argument}'.", ja: "関数「{name}」に引数「{argument}」はありません。" },
  "diagnostic.unexpected-token": { en: "Unexpected token.", ja: "予期しないtokenです。" },
  "diagnostic.invalid-expression": { en: "Invalid expression.", ja: "式が不正です。" },
  "diagnostic.duplicate-binding": { en: "Binding '{name}' is declared more than once.", ja: "binding「{name}」が同じスコープ内で複数回宣言されています。" },
  "diagnostic.binding-cycle": { en: "Binding '{name}' has a cycle: {cycle}.", ja: "binding「{name}」は循環参照しています: {cycle}" },
  "diagnostic.forward-binding-reference": { en: "'{referencedName}' is declared later and cannot be referenced yet.", ja: "「{referencedName}」はこの位置より後で宣言されているため、まだ参照できません。" },
  "diagnostic.self-initialization": { en: "Binding '{name}' references itself during initialization.", ja: "binding「{name}」は自身の初期化式内で自分自身を参照しています。" },
  "diagnostic.undefined-binding": { en: "Undefined binding '{referencedName}'.", ja: "未定義の変数「{referencedName}」を参照しています。" },
  "diagnostic.source-namespace-collision": { en: "Names '{name}' collide in the same lexical scope: {firstKind} at line {firstLine} and {secondKind}.", ja: "同じlexical scopeで名前「{name}」が衝突しています: {firstKind}(行 {firstLine}) と {secondKind}。" },
  "diagnostic.unused-drawing-modifier": { en: "Drawing Modifier '{name}' is not used anywhere.", ja: "Drawing Modifier「{name}」はどこからも使用されていません。" },
  "diagnostic.invalid-drawing-profile-reference": { en: "Invalid Drawing Profile reference '{profile}'.", ja: "Drawing Profile参照「{profile}」が不正です。" },
  "diagnostic.duplicate-drawing-profile-override": { en: "Drawing Profile '{profile}' may be specified only once.", ja: "Drawing Profile「{profile}」は1つだけ指定できます。" },
  "diagnostic.geometry-array-const-only": { en: "Geometry arrays must be declared with const.", ja: "geometry arrayはconstで宣言してください。" },
  "diagnostic.geometry-array-empty-member": { en: "A geometry array member is empty.", ja: "geometry array memberが空です。" },
  "diagnostic.geometry-array-expression-empty": { en: "The geometry array expression is empty.", ja: "geometry array式が空です。" },
  "diagnostic.geometry-array-invalid-expression": { en: "Invalid geometry array expression.", ja: "geometry array式が不正です。" },
  "diagnostic.geometry-array-invalid-member": { en: "Invalid geometry array member.", ja: "geometry array memberが不正です。" },
  "diagnostic.geometry-array-invalid-reference": { en: "Invalid geometry array reference.", ja: "geometry array参照が不正です。" },
  "diagnostic.geometry-array-member-not-geometry": { en: "Reference '{member}' is not a geometry value.", ja: "参照先「{member}」はgeometry valueではありません。" },
  "diagnostic.geometry-array-member-type-mismatch": { en: "Geometry array member '{member}' has the wrong type (expected {expected}, got {actual}).", ja: "geometry array member「{member}」の型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.geometry-array-nested-array": { en: "Geometry arrays cannot contain nested arrays.", ja: "geometry arrayを入れ子にできません。" },
  "diagnostic.geometry-array-reference-not-array": { en: "Reference '{reference}' is not a geometry array.", ja: "参照先「{reference}」はgeometry arrayではありません。" },
  "diagnostic.geometry-array-trailing-token": { en: "Unexpected token after the geometry array.", ja: "geometry arrayの後に余分なtokenがあります。" },
  "diagnostic.geometry-array-unclosed-literal": { en: "The geometry array literal is not closed.", ja: "geometry array literalが閉じられていません。" },
  "diagnostic.geometry-array-assignability-mismatch": { en: "Geometry array type '{actual}' is not assignable to '{expected}'.", ja: "geometry array型「{actual}」を「{expected}」に代入できません。" },
  "diagnostic.geometry-array-parameter-default": { en: "Geometry array Module parameters cannot have defaults.", ja: "geometry array型Module parameterにdefaultは指定できません。" },
  "diagnostic.record-field-array-unsupported": { en: "Record fields cannot use array types in nui 1.", ja: "record fieldのarray型はnui 1では使用できません。" },
  "diagnostic.record-field-default-unsupported": { en: "Record fields cannot use defaults in nui 1.", ja: "record fieldのdefaultはnui 1では使用できません。" },
  "diagnostic.record-field-duplicate": { en: "Record field '{name}' is duplicated.", ja: "record field「{name}」が重複しています。" },
  "diagnostic.record-field-geometry-unsupported": { en: "Record fields cannot use geometry type '{type}'.", ja: "record fieldにgeometry型「{type}」は使用できません。" },
  "diagnostic.record-field-invalid-shape": { en: "Record fields must use the form 'name: type'.", ja: "record fieldは「名前: 型」の形式で指定してください。" },
  "diagnostic.record-field-invalid-type": { en: "Record field type '{type}' is invalid.", ja: "record fieldの型「{type}」が不正です。" },
  "diagnostic.record-field-missing-type": { en: "Record fields require a scalar type annotation.", ja: "record fieldにはscalar型注釈が必要です。" },
  "diagnostic.record-field-nested-unsupported": { en: "Nested record field type '{type}' is not supported.", ja: "nested record型「{type}」はサポートされていません。" },
  "diagnostic.record-field-optional-unsupported": { en: "Optional record fields are not supported in nui 1.", ja: "optional record fieldはnui 1では使用できません。" },
  "diagnostic.record-invalid-name": { en: "A record definition requires a bare identifier name.", ja: "record definitionには裸の識別子名が必要です。" },
  "diagnostic.record-missing-field-list": { en: "A record definition requires a field list.", ja: "record definitionにはfield listが必要です。" },
  "diagnostic.record-trailing-token": { en: "Unexpected token after the record field list.", ja: "record definitionの後に余分なtokenがあります。" },
  "diagnostic.record-unclosed-field-list": { en: "The record field list is not closed.", ja: "record field listが閉じられていません。" },
  "diagnostic.record-field-invalid-traversal": { en: "Record field traversal '{target}' is invalid.", ja: "record field「{target}」のtraversalが不正です。" },
  "diagnostic.record-field-unavailable": { en: "Record field '{target}' is unavailable here.", ja: "record field「{target}」はこの位置では利用できません。" },
  "diagnostic.record-field-unknown": { en: "Record '{record}' has no field '{field}'.", ja: "record「{record}」にfield「{field}」はありません。" },
  "diagnostic.record-constructor-duplicate-field": { en: "Record constructor field '{field}' is duplicated.", ja: "record constructorのfield「{field}」が重複しています。" },
  "diagnostic.record-constructor-missing-field": { en: "Required field '{field}' is missing from record constructor '{record}'.", ja: "record constructor「{record}」に必須field「{field}」がありません。" },
  "diagnostic.record-constructor-positional-argument": { en: "Record constructors accept named arguments only.", ja: "record constructorの引数はnamed-onlyです。" },
  "diagnostic.record-constructor-unknown-field": { en: "Record '{record}' has no constructor field '{field}'.", ja: "record「{record}」にconstructor field「{field}」はありません。" },
  "diagnostic.record-value-ambiguous": { en: "Record value reference '{name}' is ambiguous.", ja: "record value参照「{name}」が曖昧です。" },
  "diagnostic.record-value-forward-reference": { en: "Record value '{name}' is declared later.", ja: "record value「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.import-root-unaddressable": { en: "The relative import path '{path}' cannot be resolved from the importer.", ja: "import元から相対path「{path}」を解決できません。" },
  "diagnostic.import-missing": { en: "The imported file '{path}' was not found.", ja: "import先「{path}」が見つかりません。" },
  "diagnostic.import-unreadable": { en: "The imported file '{path}' could not be read.", ja: "import先「{path}」を読み込めません。" },
  "diagnostic.import-load-stale": { en: "The imported file '{path}' load is stale.", ja: "import先「{path}」の読み込み結果がstaleです。" },
  "diagnostic.import-load-canceled": { en: "Loading the imported file '{path}' was canceled.", ja: "import先「{path}」の読み込みがcancelされました。" },
  "diagnostic.import-invalid-source": { en: "The imported file '{path}' is not valid nui 1 source.", ja: "import先「{path}」は有効なnui 1 sourceではありません。" },
  "diagnostic.import-invalid-dependency": { en: "The imported dependency graph for '{path}' is invalid.", ja: "import先「{path}」のdependency graphが無効です。" },
  "diagnostic.import-cycle": { en: "An import cycle was detected: {chain}.", ja: "import cycleを検出しました: {chain}。" },
  "diagnostic.invalid-import-syntax": { en: "Invalid import syntax.", ja: "import文の形式が不正です。" },
  "diagnostic.invalid-import-path": { en: "The import path is invalid.", ja: "import pathが不正です。" },
  "diagnostic.invalid-import-alias": { en: "The import alias is invalid.", ja: "import aliasが不正です。" },
  "diagnostic.missing-import-alias": { en: "An import alias is required.", ja: "import aliasが必要です。" },
  "diagnostic.invalid-file-reexport": { en: "Invalid file re-export.", ja: "file re-exportが不正です。" },
  "diagnostic.file-reexport-top-level-only": { en: "File re-exports are allowed only at the document top level.", ja: "file re-exportは文書のトップレベルにのみ指定できます。" },
  "diagnostic.module-recursion": { en: "A Module recursion cycle was detected for '{name}'.", ja: "「{name}」のModule recursion cycleを検出しました。" },
  "diagnostic.module-semantic-invalid": { en: "The Module semantics are invalid.", ja: "Moduleの意味解析が不正です。" },
  "diagnostic.module-duplicate-export": { en: "The Module export name '{name}' is duplicated.", ja: "Module export名「{name}」が重複しています。" },
  "diagnostic.module-invalid-export": { en: "The Module export is invalid.", ja: "Module exportが不正です。" },
  "diagnostic.module-forbidden-body-statement": { en: "The '{statement}' statement is not allowed in a Module body.", ja: "「{statement}」文はModule bodyでは使用できません。" },
  "diagnostic.module-invalid-set-target": { en: "The Module set target '{target}' is invalid.", ja: "Moduleのset対象「{target}」が不正です。" },
  "diagnostic.module-optional-value-required": { en: "Check optional Module parameter '{name}' before using it.", ja: "optional Module parameter「{name}」を確認してから使用してください。" },
  "diagnostic.module-geometry-parameter-mutation": { en: "Geometry Module parameter '{target}' cannot be mutated here.", ja: "geometry Module parameter「{target}」はここでは変更できません。" },
  "diagnostic.module-geometry-type-mismatch": { en: "Module geometry reference '{target}' has the wrong type.", ja: "Module geometry参照「{target}」の型が一致しません。" },
  "diagnostic.duplicate-public-export": { en: "The public export name '{name}' is duplicated.", ja: "公開export名「{name}」が重複しています。" },
  "diagnostic.invalid-reexport-target": { en: "The re-export target '{importAlias}' could not be resolved safely.", ja: "re-export元「{importAlias}」を安全に解決できません。" },
  "diagnostic.private-reexport-target": { en: "The target '{importAlias}::{exportedName}' is private and cannot be re-exported.", ja: "「{importAlias}::{exportedName}」は公開されていないためre-exportできません。" },
  "diagnostic.missing-reexport-target": { en: "The public re-export target '{importAlias}::{exportedName}' does not exist.", ja: "「{importAlias}::{exportedName}」に対応する公開宣言がありません。" },
  "diagnostic.builtin-geometry-argument-invalid": { en: "The geometry argument is invalid.", ja: "geometry引数が不正です。" },
  "diagnostic.builtin-geometry-argument-invalid-reference": { en: "Geometry reference '{reference}' is invalid.", ja: "geometry参照「{reference}」が不正です。" },
  "diagnostic.builtin-geometry-argument-invalid-direct": { en: "Geometry argument to '{function}' must be a direct {expected} reference.", ja: "「{function}」のgeometry引数は{expected}の直接参照である必要があります。" },
  "diagnostic.builtin-geometry-argument-invalid-property": { en: "Geometry property '{reference}' cannot be used as a {expected} argument.", ja: "geometry property「{reference}」は{expected}引数として使用できません。" },
  "diagnostic.builtin-geometry-type-mismatch": { en: "The geometry argument has the wrong type (expected {expected}, got {actual}).", ja: "geometry引数の型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.evaluation-failed": { en: "Evaluation failed.", ja: "評価に失敗しました。" },
  "diagnostic.runtime.poisoned-binding": { en: "Evaluation failed and this binding is disabled.", ja: "評価に失敗し、このbindingは無効化されています。" },
  "diagnostic.runtime.evaluation-binding-unavailable": { en: "The referenced binding is unavailable.", ja: "参照先のbindingを解決できません。" },
  "diagnostic.runtime.evaluation-runtime-value-type-mismatch": { en: "The runtime value type does not match its declaration.", ja: "実行時の値の型が宣言と一致しません。" },
  "diagnostic.runtime.evaluation-binding-cycle-guard": { en: "A runtime binding cycle was detected.", ja: "実行時のbinding循環参照が検出されました。" },
  "diagnostic.runtime.evaluation-binding-version-unavailable": { en: "The required set value has not been evaluated yet.", ja: "必要なsetの値がまだ評価されていません。" },
  "diagnostic.runtime.evaluation-divide-by-zero": { en: "Division by zero occurred.", ja: "0での除算が発生しました。" },
  "diagnostic.runtime.evaluation-remainder-by-zero": { en: "Remainder by zero occurred.", ja: "0での剰余が発生しました。" },
  "diagnostic.runtime.evaluation-invalid-builtin-argument": { en: "A builtin function argument is invalid.", ja: "組み込み関数の引数が不正です。" },
  "diagnostic.runtime.evaluation-geometry-builtin-unavailable": { en: "The geometry argument is unavailable.", ja: "組み込み関数のgeometry引数を評価できません。" },
  "diagnostic.runtime.evaluation-geometry-builtin-disabled.target": { en: "'{target}' is disabled and cannot be used as a geometry argument. Enable '{base}' or choose another reference.", ja: "「{target}」は評価OFFのためgeometry引数として利用できません。「{base}」を評価ONにするか、参照先を変更してください。" },
  "diagnostic.runtime.evaluation-geometry-builtin-disabled": { en: "A geometry argument is disabled.", ja: "組み込み関数のgeometry引数がdisabledのため利用できません。" },
  "diagnostic.runtime.evaluation-zero-length-line": { en: "A zero-length line cannot be used here.", ja: "長さ0のlineはここでは使用できません。" },
  "diagnostic.runtime.evaluation-sqrt-negative-input": { en: "The sqrt argument must be at least zero.", ja: "sqrtの引数は0以上である必要があります。" },
  "diagnostic.runtime.evaluation-round-to-non-positive-step": { en: "The roundTo step must be greater than zero.", ja: "roundToのstepは0より大きい必要があります。" },
  "diagnostic.runtime.evaluation-is-close-negative-tolerance": { en: "The isClose tolerance must be at least zero.", ja: "isCloseのtoleranceは0以上である必要があります。" },
  "diagnostic.runtime.evaluation-tan-odd-multiple-of-90": { en: "tan is undefined at 90° + 180° × n.", ja: "tanは90°+180°×nでは定義できません。" },
  "diagnostic.runtime.evaluation-asin-out-of-range": { en: "The asin argument must be between -1 and 1.", ja: "asinの引数は-1以上1以下である必要があります。" },
  "diagnostic.runtime.evaluation-acos-out-of-range": { en: "The acos argument must be between -1 and 1.", ja: "acosの引数は-1以上1以下である必要があります。" },
  "diagnostic.runtime.evaluation-non-finite-result": { en: "The calculation produced an invalid number.", ja: "計算結果が数値として不正です。" },
  "diagnostic.runtime.evaluation-static-type-null": { en: "The type could not be determined.", ja: "型を確定できませんでした。" },
  "diagnostic.runtime.evaluation-numeric-adapter-failure": { en: "Numeric evaluation failed.", ja: "数値の評価に失敗しました。" },
  "diagnostic.runtime.evaluation-geometry-property-unavailable": { en: "The element property is unavailable at this position.", ja: "要素プロパティはこの位置では評価できません。" },
  "diagnostic.required-value-missing": { en: "A required value is missing.", ja: "必須の値がありません。" },
  "diagnostic.revalidation-failed": { en: "The source changed before this diagnostic could be applied.", ja: "この診断を適用する前にSourceが変更されました。" },
  "diagnostic.missing-declared-type": { en: "A type annotation is required.", ja: "型注釈が必要です。" },
  "diagnostic.invalid-number-type-options": { en: "The number type options are invalid.", ja: "number型の設定が不正です。" },
  "diagnostic.geometry-property-invalid": { en: "Geometry property reference '{target}' is invalid.", ja: "geometry property参照「{target}」が不正です。" },
  "diagnostic.invalid-set-target": { en: "Set target '{name}' is invalid.", ja: "set対象「{name}」が不正です。" },
  "diagnostic.set-rhs-unresolved": { en: "Set value reference '{name}' could not be resolved.", ja: "setの値の参照「{name}」を解決できません。" },
  "diagnostic.set-rhs-invalid-reference": { en: "Set reference '{name}' is invalid.", ja: "setの参照「{name}」が不正です。" },
  "diagnostic.const-assignment": { en: "Const binding '{name}' cannot be assigned.", ja: "const binding「{name}」には代入できません。" },
  "diagnostic.property-binding-not-supported": { en: "This property does not support a binding.", ja: "このpropertyはbindingをサポートしていません。" },
  "diagnostic.property-binding-unresolved": { en: "Property binding reference '{name}' could not be resolved.", ja: "property bindingの参照「{name}」を解決できません。" },
  "diagnostic.property-binding-invalid": { en: "Property binding reference '{name}' is invalid.", ja: "property bindingの参照「{name}」が不正です。" },
  "diagnostic.property-binding-type-mismatch": { en: "Property binding '{name}' has the wrong type (expected {expected}, got {actual}).", ja: "property binding「{name}」の型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.conditional-group-condition-unresolved": { en: "Conditional group condition reference '{name}' could not be resolved.", ja: "条件グループのconditionの参照「{name}」を解決できません。" },
  "diagnostic.conditional-group-condition-invalid": { en: "Conditional group condition reference '{name}' is invalid.", ja: "条件グループのconditionの参照「{name}」が不正です。" },
  "diagnostic.conditional-group-condition-type-mismatch": { en: "The conditional group condition must be boolean.", ja: "条件グループのconditionはbooleanである必要があります。" },
  "diagnostic.numeric-binding-unresolved": { en: "Numeric binding reference '{name}' could not be resolved.", ja: "数値bindingの参照「{name}」を解決できません。" },
  "diagnostic.numeric-binding-type-mismatch": { en: "Numeric binding has the wrong type (expected {expected}, got {actual}).", ja: "数値bindingの型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.numeric-binding-mapping": { en: "The numeric binding mapping is invalid.", ja: "数値bindingの対応付けが不正です。" },
  "diagnostic.numeric-binding-iteration-reference": { en: "Iteration reference '{name}' is invalid here.", ja: "この位置のiteration参照「{name}」が不正です。" },
  "diagnostic.text-template-hole-unresolved": { en: "Text template reference '{reference}' could not be resolved.", ja: "text templateの参照「{reference}」を解決できません。" },
  "diagnostic.text-template-hole-invalid": { en: "Text template reference '{reference}' is invalid.", ja: "text templateの参照「{reference}」が不正です。" },
  "diagnostic.interpolation-type-mismatch": { en: "The interpolated value has the wrong type (got {actual}).", ja: "interpolationされた値の型が一致しません（実際: {actual}）。" },
  "diagnostic.invalid-literal-token": { en: "Invalid literal.", ja: "literalが不正です。" },
  "diagnostic.invalid-string-escape": { en: "Invalid string escape.", ja: "文字列escapeが不正です。" },
  "diagnostic.missing-operand": { en: "An expression operand is missing.", ja: "式のoperandがありません。" },
  "diagnostic.unterminated-group": { en: "The expression group is not closed.", ja: "式のgroupが閉じられていません。" },
  "diagnostic.trailing-token": { en: "Unexpected trailing token.", ja: "予期しない末尾tokenです。" },
  "diagnostic.expression-depth-exceeded": { en: "The expression is too deeply nested.", ja: "式の入れ子が深すぎます。" },
  "diagnostic.chained-comparison-not-supported": { en: "Chained comparisons are not supported.", ja: "比較演算子の連鎖はサポートされていません。" },
  "diagnostic.geometry-property-in-typed-expression": { en: "Geometry properties cannot be used in this expression.", ja: "この式ではgeometry propertyを使用できません。" },
  "diagnostic.unclosed-call": { en: "The call is not closed.", ja: "callが閉じられていません。" },
  "diagnostic.empty-argument": { en: "An argument is empty.", ja: "引数が空です。" },
  "diagnostic.missing-argument-comma": { en: "Arguments must be separated by commas.", ja: "引数はcommaで区切ってください。" },
  "diagnostic.import-top-level-only": { en: "Imports are allowed only at the document top level.", ja: "importは文書のトップレベルにのみ指定できます。" },
  "diagnostic.module-export-top-level-only": { en: "Module exports are allowed only at the module top level.", ja: "Module exportはModuleのトップレベルにのみ指定できます。" },
  "diagnostic.module-optional-default-conflict": { en: "Optional Module parameter '{parameter}' cannot have a default.", ja: "optional Module parameter「{parameter}」にdefaultは指定できません。" },
  "diagnostic.missing-module-instance-equals": { en: "A Module instance requires an initializer.", ja: "Module instanceには初期化式が必要です。" },
  "diagnostic.invalid-module-instance-state": { en: "The Module instance state is invalid.", ja: "Module instanceのstateが不正です。" },
  "diagnostic.state-hidden-unsupported": { en: "Construction '{construction}' cannot use state: hidden because it has no own geometry. Use visible or disabled.", ja: "{construction}は自身の図形を持たないためstate: hiddenを指定できません。visibleかdisabledを使ってください。" },
  "diagnostic.color-unsupported": { en: "Construction '{construction}' cannot use color because it has no own geometry.", ja: "{construction}は自身の図形を持たないためcolorを指定できません。" },
  "diagnostic.source-rewrite-failed": { en: "The source could not be rewritten safely.", ja: "Sourceを安全に書き換えられません。" },
  "diagnostic.unsafe-rewrite": { en: "The source rewrite is unsafe.", ja: "Sourceの書き換えが安全ではありません。" },
  "diagnostic.unsafe-source-span": { en: "The source span is unsafe.", ja: "Source spanが安全ではありません。" },
  "diagnostic.record-type-not-record": { en: "Type '{name}' is not a record definition.", ja: "型名「{name}」はrecord definitionではありません。" },
  "diagnostic.record-type-forward-reference": { en: "Record type '{name}' is declared later.", ja: "record型「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.record-type-ambiguous": { en: "Record type reference '{name}' is ambiguous.", ja: "record型参照「{name}」が曖昧です。" },
  "diagnostic.record-type-undefined": { en: "Record type '{name}' is undefined.", ja: "record型「{name}」が未定義です。" },
  "diagnostic.record-definition-not-top-level": { en: "Record definitions are allowed only at the document top level.", ja: "record definitionは文書のトップレベルにのみ宣言できます。" },
  "diagnostic.record-parameter-default-unsupported": { en: "Record-typed Module parameters cannot have defaults.", ja: "record型Module parameterにdefaultは指定できません。" },
  "diagnostic.record-let-unsupported": { en: "Record-typed bindings must use const in nui 1.", ja: "record型bindingはnui 1ではconstのみです。" },
  "diagnostic.record-reference-invalid": { en: "The record reference is invalid.", ja: "record参照が不正です。" },
  "diagnostic.record-reference-not-record": { en: "Reference '{name}' is not a record value.", ja: "参照先「{name}」はrecord valueではありません。" },
  "diagnostic.record-nominal-type-mismatch": { en: "Record value '{name}' does not match expected record type '{expected}'.", ja: "record value「{name}」は期待されるrecord型「{expected}」と一致しません。" },
  "diagnostic.record-constructor-invalid": { en: "The record value initializer is invalid.", ja: "record valueの初期化式が不正です。" },
  "diagnostic.record-constructor-not-record": { en: "Constructor target '{name}' is not a record.", ja: "constructor対象「{name}」はrecordではありません。" },
  "diagnostic.record-constructor-forward-reference": { en: "Record constructor '{name}' is declared later.", ja: "record constructor「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.record-constructor-ambiguous": { en: "Record constructor reference '{name}' is ambiguous.", ja: "record constructor参照「{name}」が曖昧です。" },
  "diagnostic.record-constructor-undefined": { en: "Record constructor '{name}' is undefined.", ja: "record constructor「{name}」が未定義です。" },
  "diagnostic.record-constructor-invalid-argument": { en: "The record constructor argument is invalid.", ja: "record constructor引数が不正です。" },
  "diagnostic.record-set-unsupported": { en: "Record values cannot be assigned with set.", ja: "record valueにはsetで代入できません。" },
  "diagnostic.module-private-member": { en: "Module member '{target}' is not exported.", ja: "Module member「{target}」はexportされていません。" },
  "diagnostic.module-array-outer-capture": { en: "A Module body cannot capture an outer geometry array.", ja: "Module bodyから外側のgeometry arrayをcaptureできません。" },
  "diagnostic.module-undefined-export": { en: "Module export '{target}' is undefined.", ja: "Module export「{target}」が未定義です。" },
  "diagnostic.geometry-array-member-unresolved": { en: "Geometry array member '{member}' could not be resolved.", ja: "geometry array member「{member}」を解決できません。" },
  "diagnostic.geometry-array-reference-forward": { en: "Geometry array '{reference}' is declared later.", ja: "geometry array「{reference}」はこの位置より後で宣言されています。" },
  "diagnostic.geometry-array-reference-ambiguous": { en: "Geometry array reference '{reference}' is ambiguous.", ja: "geometry array参照「{reference}」が曖昧です。" },
  "diagnostic.geometry-array-member-forward": { en: "Geometry array member '{member}' is declared later.", ja: "geometry array member「{member}」はこの位置より後で宣言されています。" },
  "diagnostic.geometry-array-member-ambiguous": { en: "Geometry array member reference '{member}' is ambiguous.", ja: "geometry array member参照「{member}」が曖昧です。" },
  "diagnostic.geometry-array-member-invalidTraversal": { en: "Geometry array member traversal '{member}' is invalid.", ja: "geometry array member「{member}」のtraversalが不正です。" },
  "diagnostic.geometry-array-reference-invalidTraversal": { en: "Geometry array reference traversal '{reference}' is invalid.", ja: "geometry array参照「{reference}」のtraversalが不正です。" },
  "diagnostic.module-ambiguous-callee": { en: "Module callee '{name}' is ambiguous.", ja: "Module callee「{name}」が曖昧です。" },
  "diagnostic.module-ambiguous-geometry-reference": { en: "Module geometry reference '{name}' is ambiguous.", ja: "Module geometry参照「{name}」が曖昧です。" },
  "diagnostic.module-ambiguous-instance-reference": { en: "Module instance reference '{name}' is ambiguous.", ja: "Module instance参照「{name}」が曖昧です。" },
  "diagnostic.module-ambiguous-reference": { en: "Module scalar reference '{name}' is ambiguous.", ja: "Module scalar参照「{name}」が曖昧です。" },
  "diagnostic.module-callee-not-definition": { en: "'{name}' is not a Module definition.", ja: "「{name}」はModule definitionではありません。" },
  "diagnostic.module-default-invalid-reference": { en: "Module default reference '{name}' is not a scalar binding.", ja: "Module defaultの参照先「{name}」はscalar bindingではありません。" },
  "diagnostic.module-default-parameter-order": { en: "Module defaults may reference only earlier parameters; '{name}' is later.", ja: "Module defaultでは先に宣言されたparameterのみ参照できます。「{name}」は後のparameterです。" },
  "diagnostic.module-document-binding-unavailable": { en: "Document scalar binding '{name}' is unavailable in this Module.", ja: "このModuleではdocument scalar「{name}」のbindingを利用できません。" },
  "diagnostic.module-duplicate-argument": { en: "Module argument '{argument}' is duplicated.", ja: "Module引数「{argument}」が重複しています。" },
  "diagnostic.module-duplicate-function-argument": { en: "The Module function argument is duplicated.", ja: "Module関数引数が重複しています。" },
  "diagnostic.module-forward-callee": { en: "Module callee '{name}' is declared later.", ja: "Module callee「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-forward-geometry-reference": { en: "Geometry '{name}' is declared later.", ja: "geometry「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-forward-instance-reference": { en: "Module instance '{name}' is declared later.", ja: "module instance「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-forward-reference": { en: "Module scalar '{name}' is declared later.", ja: "module scalar「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-function-arity-mismatch": { en: "The Module function argument count is incorrect.", ja: "Module関数の引数の数が不正です。" },
  "diagnostic.module-function-call-style-mismatch": { en: "The Module function call style is unsupported.", ja: "Module関数の呼び出し形式が不正です。" },
  "diagnostic.module-geometry-default": { en: "Geometry Module parameter '{name}' cannot have a default.", ja: "geometry Module parameter「{name}」にはdefaultを指定できません。" },
  "diagnostic.module-geometry-none": { en: "Geometry {expected} reference cannot be none here.", ja: "この位置ではgeometry {expected} referenceにnoneを指定できません。" },
  "diagnostic.module-geometry-property-reference": { en: "The Module geometry property reference is invalid.", ja: "Module geometry property参照が不正です。" },
  "diagnostic.module-geometry-property-type-mismatch": { en: "Module geometry property reference '{target}' has the wrong type.", ja: "Module geometry property参照「{target}」の型が一致しません。" },
  "diagnostic.module-geometry-reference-in-default": { en: "Geometry '{name}' is not allowed in a Module default.", ja: "Module defaultではgeometry「{name}」を参照できません。" },
  "diagnostic.module-geometry-reference-in-scalar": { en: "Geometry '{name}' is not allowed in a scalar expression.", ja: "scalar expressionではgeometry「{name}」を参照できません。" },
  "diagnostic.module-has-value-argument": { en: "The hasValue argument is invalid.", ja: "hasValue引数が不正です。" },
  "diagnostic.module-has-value-parameter": { en: "'{name}' is not an optional Module parameter for hasValue.", ja: "「{name}」はhasValueで使用できるoptional Module parameterではありません。" },
  "diagnostic.module-invalid-choice-literal": { en: "The Module choice value is invalid.", ja: "Module choice値が不正です。" },
  "diagnostic.module-invalid-reference": { en: "Module reference '{name}' is invalid.", ja: "Module参照「{name}」が不正です。" },
  "diagnostic.module-missing-argument": { en: "Required Module argument '{parameter}' is missing.", ja: "必須のModule引数「{parameter}」がありません。" },
  "diagnostic.module-missing-function-argument": { en: "A required Module function argument is missing.", ja: "必須のModule関数引数がありません。" },
  "diagnostic.module-outer-capture": { en: "A Module body cannot capture outer value '{name}'.", ja: "Module bodyから外側の値「{name}」をcaptureできません。" },
  "diagnostic.module-parameter-collision": { en: "Module parameter '{name}' collides with another name.", ja: "Module parameter「{name}」の名前が衝突しています。" },
  "diagnostic.module-parameter-duplicate": { en: "Module parameter '{parameter}' is duplicated.", ja: "Module parameter「{parameter}」が重複しています。" },
  "diagnostic.module-record-ambiguous-reference": { en: "Module record reference '{name}' is ambiguous.", ja: "Module record参照「{name}」が曖昧です。" },
  "diagnostic.module-record-field-unknown": { en: "Record '{record}' has no field '{field}'.", ja: "record「{record}」にfield「{field}」はありません。" },
  "diagnostic.module-record-forward-reference": { en: "Module record value '{name}' is declared later.", ja: "Module record value「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-record-invalid-reference": { en: "Module record value '{name}' is not a namespace.", ja: "Module record value「{name}」はnamespaceではありません。" },
  "diagnostic.module-record-reference-invalid": { en: "The Module record reference is invalid.", ja: "Module record参照が不正です。" },
  "diagnostic.module-record-value-in-geometry": { en: "Record value '{name}' cannot be used as geometry.", ja: "record value「{name}」をgeometryとして使用できません。" },
  "diagnostic.module-record-value-in-scalar": { en: "Record value '{name}' cannot be used as a scalar.", ja: "record value「{name}」をscalarとして使用できません。" },
  "diagnostic.module-resolved-callee": { en: "The Module callee resolved unexpectedly.", ja: "Module calleeの解決結果が不正です。" },
  "diagnostic.module-scalar-geometry-reference": { en: "Scalar expressions cannot reference geometry '{name}'.", ja: "scalar expressionからgeometry「{name}」を参照できません。" },
  "diagnostic.module-scalar-type-mismatch": { en: "The Module scalar type does not match.", ja: "Module scalarの型が一致しません。" },
  "diagnostic.module-undefined-instance-reference": { en: "Module instance '{name}' is undefined.", ja: "module instance「{name}」が未定義です。" },
  "diagnostic.module-undefined-geometry-reference": { en: "Geometry '{name}' is undefined.", ja: "geometry「{name}」が未定義です。" },
  "diagnostic.module-undefined-reference": { en: "Module scalar '{name}' is undefined.", ja: "module scalar「{name}」が未定義です。" },
  "diagnostic.module-unknown-argument": { en: "Module '{module}' has no argument '{argument}'.", ja: "module「{module}」にargument「{argument}」はありません。" },
  "diagnostic.module-unknown-function": { en: "The Module function is unknown.", ja: "Module関数が不明です。" },
  "diagnostic.module-unknown-function-argument": { en: "The Module function argument is unknown.", ja: "Module関数引数が不明です。" },
  "diagnostic.module-unknown-geometry-property": { en: "Geometry property '{property}' is unknown.", ja: "geometry property「{property}」が不明です。" },
  "diagnostic.module-unresolved-callee": { en: "Module '{name}' could not be resolved.", ja: "Module「{name}」を解決できません。" },
  "diagnostic.module-unterminated-string": { en: "The Module string is not closed.", ja: "Moduleの文字列が閉じられていません。" },
  "diagnostic.module-physical-newline-in-string": { en: "A Module string cannot contain a physical newline.", ja: "Moduleの文字列に改行を含めることはできません。" },
  "diagnostic.module-invalid-string-escape": { en: "The Module string escape is invalid.", ja: "Moduleの文字列escapeが不正です。" },
  "diagnostic.module-interpolation-nested-not-supported": { en: "Nested Module interpolation is not supported.", ja: "Module interpolationの入れ子はサポートされていません。" },
  "diagnostic.module-interpolation-empty": { en: "The Module interpolation is empty.", ja: "Module interpolationが空です。" },
  "diagnostic.module-unterminated-interpolation": { en: "The Module interpolation is not closed.", ja: "Module interpolationが閉じられていません。" },
  "diagnostic.related.declaration": { en: "Related declaration", ja: "関連する宣言" },
  "diagnostic.related.parameter-declaration": { en: "Related parameter declaration", ja: "関連するparameter宣言" },
  "diagnostic.related.expected-parameter-type": { en: "Expected parameter type", ja: "期待されるparameter型" },
  "diagnostic.related.first-parameter": { en: "First parameter with this name", ja: "この名前の最初のparameter" },
  "diagnostic.related.iteration-declaration": { en: "Related iteration declaration", ja: "関連するiteration宣言" },
  "diagnostic.related.module-member-declaration": { en: "Related Module member declaration", ja: "関連するModule member宣言" },
  "diagnostic.related.geometry-declaration": { en: "Related geometry declaration", ja: "関連するgeometry宣言" },
  "diagnostic.related.record-value": { en: "Related record value", ja: "関連するrecord value" },
  "diagnostic.related.module-recursion": { en: "Related call in the Module recursion cycle", ja: "Module recursion cycleに含まれる関連call" },
  "diagnostic.related.first-argument": { en: "First argument with this name", ja: "この名前の最初のargument" },
  "diagnostic.related.called-module-definition": { en: "Called Module definition", ja: "呼び出されたModule定義" }
} satisfies TranslationCatalog;

export type DiagnosticPresentation = DslDiagnosticPresentation;
export type DiagnosticLocalizationKey = keyof typeof diagnosticTranslationCatalog;

const translatePresentation = (
  presentation: DiagnosticPresentation,
  displayLanguage: string
): string | null => {
  const translated = createTranslator(diagnosticTranslationCatalog, resolveLocale(displayLanguage))(
    presentation.key,
    presentation.parameters
  );
  return translated === presentation.key ? null : translated;
};

export const diagnosticTextFor = (
  diagnostic: Pick<CompilerDiagnostic, "message" | "presentation">,
  displayLanguage: string
): string => diagnostic.presentation
  ? translatePresentation(diagnostic.presentation, displayLanguage) ?? diagnostic.message
  : diagnostic.message;

export const diagnosticRelatedTextFor = (
  related: Pick<CompilerDiagnosticRelatedInformation, "message" | "presentation">,
  displayLanguage: string
): string => related.presentation
  ? translatePresentation(related.presentation, displayLanguage) ?? related.message
  : related.message;

export const diagnosticSuffixTextFor = (
  presentation: DiagnosticPresentation | undefined,
  displayLanguage: string
): string | null => presentation ? translatePresentation(presentation, displayLanguage) : null;

export const diagnosticMessageFor = (
  diagnostic: Pick<CompilerDiagnostic, "message" | "presentation" | "suffixPresentation">,
  displayLanguage: string
): string => [
  diagnosticTextFor(diagnostic, displayLanguage),
  diagnosticSuffixTextFor(diagnostic.suffixPresentation, displayLanguage)
].filter((part): part is string => part !== null).join(" ");
