import type { DslDiagnosticPresentation } from "@nuinuicad/nui-language";
import type { CompilerDiagnostic, CompilerDiagnosticRelatedInformation } from "./compilerDiagnostics";
import { createTranslator, resolveLocale, type TranslationCatalog } from "./localization";

/**
 * Problems presentation is intentionally a VS Code-owned concern.  The DSL
 * and runtime layers only carry the stable key and primitive parameters; this
 * catalog is the only place where those identities become user-facing text.
 */
export const diagnosticTranslationCatalog = {
  "typoSuggestion.diagnosticSuffix": { en: "Did you mean '{candidate}'?", ja: "「{candidate}」のことですか？" },
  "diagnostic.related.first-export": { en: "First export with this name", ja: "この名前の最初のexport" },
  "diagnostic.missing-attribute-value": { en: "Argument '{parameter}' has no value.", ja: "引数「{parameter}」の値がありません。" },
  "diagnostic.unknown-dsl-keyword": { en: "Unknown DSL keyword.", ja: "不明なDSLキーワードです。" },
  "diagnostic.unknown-type": { en: "Unknown type annotation '{type}'.", ja: "不明な型注釈です: {type}" },
  "diagnostic.unknown-construction": { en: "Category '{category}' has no construction '{construction}'. Candidates: {candidates}.", ja: "category「{category}」にconstruction「{construction}」はありません。候補: {candidates}。" },
  "diagnostic.construction-category-mismatch": { en: "Construction '{construction}' does not match category '{category}'. Allowed categories: {categories}. Candidates: {candidates}.", ja: "category「{category}」とconstruction「{construction}」の組み合わせは不一致です。使用できるcategory: {categories}。候補: {candidates}。" },
  "diagnostic.unknown-construction-argument": { en: "Construction '{construction}' has no argument '{argument}'. Candidates: {candidates}.", ja: "construction「{construction}」に引数「{argument}」はありません。候補: {candidates}。" },
  "diagnostic.geometry-reference-type-mismatch": { en: "Reference '{target}' is not a line or curve.", ja: "参照先「{target}」は線・曲線ではありません。" },
  "diagnostic.geometry-value-mutation-target-unsupported": { en: "An immutable geometry value cannot be used as a mutation target.", ja: "immutable geometry value は mutation target にできません。" },
  "diagnostic.join-empty-paths": { en: "The join paths argument must contain at least one path.", ja: "join の paths には少なくとも1つの path を指定してください。" },
  "diagnostic.undefined-geometry-reference": { en: "Geometry reference '{reference}' could not be resolved.", ja: "geometry参照「{reference}」を解決できません。" },
  "diagnostic.invalid-source-reference": { en: "Invalid source reference '{reference}'.", ja: "参照「{reference}」が不正です。" },
  "diagnostic.missing-version-declaration": { en: "The document is empty. Add `nui 1` at the beginning.", ja: "文書が空です。先頭に `nui 1` が必要です。" },
  "diagnostic.version-declaration-not-first": {
    en: "The document must begin with `nui <version>`." ,
    ja: "文書の先頭は `nui <バージョン>` である必要があります。"
  },
  "diagnostic.invalid-dsl-version": { en: "Invalid DSL version: {version}", ja: "不正なDSLバージョンです: {version}" },
  "diagnostic.unsupported-dsl-version": { en: "Unsupported DSL version: {version} (supported: {supported})", ja: "未対応のDSLバージョンです: {version}(対応: {supported})" },
  "diagnostic.duplicate-version-declaration": { en: "The `nui` declaration may appear only once at the beginning of the document.", ja: "`nui` は文書の先頭に1つだけ書けます。" },
  "diagnostic.invalid-for-source-reference": { en: "A statement-for collection source must use an ordinary @reference.", ja: "statement-for の collection source は通常の @reference で指定してください。" },
  "diagnostic.carry-geometry-type-mismatch": { en: "carry '{name}' geometry {position} must match the declared type.", ja: "carry「{name}」の geometry {position} は宣言された型と一致する必要があります。" },
  "diagnostic.carry-collection-expression-invalid": { en: "carry '{name}' {collectionKind} initializer/next must match the declared collection type.", ja: "carry「{name}」の {collectionKind} initializer/next は宣言された collection 型と一致する必要があります。" },
  "diagnostic.dependency-cycle": { en: "Dependency cycle: {names}", ja: "依存関係 cycle: {names}" },
  "diagnostic.source-reference-forward": { en: "Reference '{reference}' is declared later and is not available here.", ja: "参照先「{reference}」はこの位置より後で宣言されています。" },
  "diagnostic.source-reference-ambiguous": { en: "Reference '{reference}' is ambiguous.", ja: "参照が曖昧です: {reference}" },
  "diagnostic.source-reference-invalid-traversal": { en: "Reference '{reference}' cannot traverse this kind of declaration.", ja: "参照先「{reference}」はこの種類の宣言を辿れません。" },
  "diagnostic.source-reference-undefined": { en: "Reference '{reference}' is undefined.", ja: "未定義の参照です: {reference}" },
  "diagnostic.source-reference-kind-mismatch": { en: "Reference '{reference}' is not one of the expected declaration kinds: {expected}.", ja: "参照先「{reference}」は {expected} ではありません。" },
  "diagnostic.undefined-visibility-role": { en: "Visibility role '{role}' is undefined.", ja: "未定義の表示ロールです: {role}" },
  "diagnostic.invalid-visibility-role-value": { en: "Visibility role '{role}' must be true or false.", ja: "{role} は true/false で指定してください。" },
  "diagnostic.undefined-visibility-profile": { en: "Visibility profile '{profile}' is undefined.", ja: "未定義の表示プロファイルです: {profile}" },
  "diagnostic.place-target-not-group": { en: "Place target '{reference}' is not a group.", ja: "place の参照先はグループではありません: {reference}" },
  "diagnostic.place-origin-namespace-unavailable": { en: "Place origin '{reference}' cannot be resolved without the source lexical namespace.", ja: "place origin は source lexical namespace で解決できません: {reference}" },
  "diagnostic.place-origin-unresolved": { en: "Place origin reference '{reference}' could not be resolved.", ja: "origin の参照先を解決できません: {reference}" },
  "diagnostic.place-origin-not-point": { en: "Place origin reference '{reference}' is not a point.", ja: "origin の参照先は点ではありません: {reference}" },
  "diagnostic.place-origin-outside-target-group": { en: "Place origin point '{reference}' is not inside the placed group.", ja: "origin の点は配置対象グループの内部にありません: {reference}" },
  "diagnostic.invalid-layout-scale": { en: "Layout scale must be a finite positive value.", ja: "layout scale は有限の正の値で指定してください。" },
  "diagnostic.place-position-required": { en: "Place requires `at: (x, y)`.", ja: "place には `at: (x, y)` が必要です。" },
  "diagnostic.invalid-place-mirror": { en: "Place mirror must be true or false.", ja: "place mirror は true / false で指定してください。" },
  "diagnostic.invalid-place-scale": { en: "Place scale must be a finite positive value.", ja: "place scale は有限の正の値で指定してください。" },
  "diagnostic.invalid-place-angle": { en: "Place angle must be finite.", ja: "place angle は有限の値で指定してください。" },
  "diagnostic.output-layout-unavailable": { en: "The print/svg layout declaration could not be resolved.", ja: "print/svg layout の宣言を取得できません。" },
  "diagnostic.invalid-print-paper": { en: "Print paper must be a4 or a3.", ja: "print paper は a4 または a3 で指定してください。" },
  "diagnostic.invalid-print-orientation": { en: "Orientation must be portrait or landscape.", ja: "orientation は portrait / landscape で指定してください。" },
  "diagnostic.invalid-print-overlap": { en: "Print overlap must be at least 0.", ja: "print overlap は 0 以上で指定してください。" },
  "diagnostic.print-overlap-too-large": { en: "Print overlap is too large. For {paper} {orientation}, overlap must be less than {maximum}mm.", ja: "print の overlap が大きすぎます。{paper} {orientation} では overlap を {maximum}mm 未満にしてください。" },
  "diagnostic.invalid-svg-margin": { en: "SVG margin must be at least 0.", ja: "svg margin は 0 以上で指定してください。" },
  "diagnostic.undefined-drawing-style": { en: "Style '{name}' is undefined.", ja: "未定義の style です: {name}" },
  "diagnostic.ignored-parent-in-block": { en: "The parent= attribute is ignored inside a block.", ja: "ブロック内の parent= 属性は無視されます。" },
  "diagnostic.missing-sigil": { en: "Element-property reference '{reference}' requires '@'.", ja: "要素プロパティ参照「{reference}」には「@」が必要です。" },
  "diagnostic.invalid-choice-literal": { en: "Choice literal '{value}' is not valid for {expected}.", ja: "choice literal「{value}」は{expected}では使用できません。" },
  "diagnostic.invalid-choice-type": { en: "Invalid choice type.", ja: "choice型が不正です。" },
  "diagnostic.duplicate-choice-option": { en: "Choice option '{option}' is duplicated.", ja: "choice option「{option}」が重複しています。" },
  "diagnostic.impossible-match-case": { en: "Match case '{option}' does not exist in {expected}.", ja: "match ケース「{option}」は{expected}には存在しません。" },
  "diagnostic.duplicate-match-case": { en: "Match case '{option}' is duplicated.", ja: "match ケース「{option}」が重複しています。" },
  "diagnostic.missing-match-case": { en: "Match is missing required choice cases: {options}.", ja: "match に必要なchoiceケースがありません: {options}。" },
  "diagnostic.non-choice-match-scrutinee": { en: "Match scrutinee must have a choice(...) type (got {actual}).", ja: "match のscrutineeはchoice(...)型である必要があります（実際: {actual}）。" },
  "diagnostic.scalar-type-mismatch": { en: "Type mismatch (expected {expected}, got {actual}).", ja: "型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.optional-value-required": { en: "The absence literal 'none' is only valid where an optional value is expected.", ja: "absence値「none」はoptional valueが期待される場所でのみ使用できます。" },
  "diagnostic.none-requires-optional-type": { en: "The 'none' value requires a known optional type context.", ja: "none は基底型が確定した optional 型の文脈でのみ使用できます。" },
  "diagnostic.invalid-boolean-parameter-value": { en: "Parameter '{parameter}' must be true or false.", ja: "{parameter} は true/false で指定してください。" },
  "diagnostic.invalid-numeric-parameter-steps": { en: "steps must be a list of parameter:positiveNumber entries.", ja: "steps は parameter:positiveNumber の一覧で指定してください。" },
  "diagnostic.function-arity-mismatch": { en: "Function '{name}' has the wrong number of arguments (expected {expected}, got {actual}).", ja: "関数「{name}」の引数の数が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.function-call-style-mismatch": { en: "The function call style is not supported.", ja: "関数の呼び出し形式が不正です。" },
  "diagnostic.duplicate-function-argument": { en: "Function '{name}' has a duplicate argument '{argument}'.", ja: "関数「{name}」の引数「{argument}」が重複しています。" },
  "diagnostic.missing-function-argument": { en: "Required argument '{parameter}' is missing from function '{name}'.", ja: "関数「{name}」に必須引数「{parameter}」がありません。" },
  "diagnostic.unknown-function": { en: "Unknown function '{name}'.", ja: "不明な関数「{name}」です。" },
  "diagnostic.unknown-function-argument": { en: "Function '{name}' has no argument '{argument}'.", ja: "関数「{name}」に引数「{argument}」はありません。" },
  "diagnostic.unexpected-token": { en: "Unexpected token.", ja: "予期しないtokenです。" },
  "diagnostic.invalid-expression": { en: "Invalid expression.", ja: "式が不正です。" },
  "diagnostic.duplicate-binding": { en: "Binding '{name}' is declared more than once.", ja: "binding「{name}」が同じスコープ内で複数回宣言されています。" },
  "diagnostic.binding-cycle": { en: "Binding '{name}' has a cycle: {cycle}.", ja: "binding「{name}」は循環参照しています: {cycle}" },
  "diagnostic.forward-binding-reference": { en: "'{referencedName}' is declared later and cannot be referenced yet.", ja: "「{referencedName}」はこの位置より後で宣言されているため、まだ参照できません。" },
  "diagnostic.self-initialization": { en: "Binding '{name}' references itself during initialization.", ja: "binding「{name}」は自身の初期化式内で自分自身を参照しています。" },
  "diagnostic.undefined-binding": { en: "Undefined binding '{referencedName}'.", ja: "未定義の変数「{referencedName}」を参照しています。" },
  "diagnostic.source-namespace-collision": { en: "Names '{name}' collide in the same lexical scope: {firstKind} at line {firstLine} and {secondKind}.", ja: "同じlexical scopeで名前「{name}」が衝突しています: {firstKind}(行 {firstLine}) と {secondKind}。" },
  "diagnostic.unused-drawing-style": { en: "Style '{name}' is not used anywhere.", ja: "Style「{name}」はどこからも使用されていません。" },
  "diagnostic.unused-typed-declaration": { en: "Declaration '{name}' is not used anywhere.", ja: "宣言「{name}」はどこからも使用されていません。" },
  "diagnostic.unused-module-parameter": { en: "Module parameter '{name}' is not used anywhere.", ja: "Module parameter「{name}」はどこからも使用されていません。" },
  "diagnostic.unused-private-module": { en: "Private Module '{name}' is not used anywhere.", ja: "Private Module「{name}」はどこからも使用されていません。" },
  "diagnostic.unused-import": { en: "Import alias '{name}' is not used anywhere.", ja: "import alias「{name}」はどこからも使用されていません。" },
  "diagnostic.invalid-drawing-profile-reference": { en: "Invalid Drawing Profile reference '{profile}'.", ja: "Drawing Profile参照「{profile}」が不正です。" },
  "diagnostic.duplicate-drawing-profile-override": { en: "Drawing Profile '{profile}' may be specified only once.", ja: "Drawing Profile「{profile}」は1つだけ指定できます。" },
  "diagnostic.geometry-array-const-only": { en: "Geometry arrays must be declared with const.", ja: "geometry arrayはconstで宣言してください。" },
  "diagnostic.geometry-array-empty-member": { en: "A geometry array member is empty.", ja: "geometry array memberが空です。" },
  "diagnostic.geometry-array-expression-empty": { en: "The geometry array expression is empty.", ja: "geometry array式が空です。" },
  "diagnostic.geometry-array-invalid-expression": { en: "Invalid geometry array expression.", ja: "geometry array式が不正です。" },
  "diagnostic.geometry-array-invalid-member": { en: "Invalid geometry array member.", ja: "geometry array memberが不正です。" },
  "diagnostic.geometry-array-invalid-reference": { en: "Invalid geometry array reference.", ja: "geometry array参照が不正です。" },
  "diagnostic.geometry-array-member-not-geometry": { en: "Reference '{member}' is not a geometry value.", ja: "参照先「{member}」はgeometry valueではありません。" },
  "diagnostic.geometry-array-member-type-mismatch": { en: "Geometry array member '{member}' has the wrong type (expected {expected}, got {actual}).", ja: "geometry array member「{member}」の型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.geometry-array-nested-array": { en: "Geometry arrays cannot contain nested arrays.", ja: "geometry arrayを入れ子にできません。" },
  "diagnostic.geometry-array-reference-not-array": { en: "Reference '{reference}' is not a geometry array.", ja: "参照先「{reference}」はgeometry arrayではありません。" },
  "diagnostic.geometry-array-trailing-token": { en: "Unexpected token after the geometry array.", ja: "geometry arrayの後に余分なtokenがあります。" },
  "diagnostic.geometry-array-unclosed-literal": { en: "The geometry array literal is not closed.", ja: "geometry array literalが閉じられていません。" },
  "diagnostic.geometry-array-assignability-mismatch": { en: "Geometry array type '{actual}' is not assignable to '{expected}'.", ja: "geometry array型「{actual}」を「{expected}」に代入できません。" },
  "diagnostic.geometry-array-parameter-default": { en: "Geometry array Module parameters cannot have defaults.", ja: "geometry array型Module parameterにdefaultは指定できません。" },
  "diagnostic.array-empty-member": { en: "An array member is empty.", ja: "array memberが空です。" },
  "diagnostic.array-expression-empty": { en: "The array expression is empty.", ja: "array式が空です。" },
  "diagnostic.array-invalid-expression": { en: "Invalid array expression.", ja: "array式が不正です。" },
  "diagnostic.array-invalid-member": { en: "Invalid array member.", ja: "array memberが不正です。" },
  "diagnostic.array-nested-array": { en: "Arrays cannot contain nested arrays.", ja: "arrayを入れ子にできません。" },
  "diagnostic.array-trailing-token": { en: "Unexpected token after the array.", ja: "arrayの後に余分なtokenがあります。" },
  "diagnostic.array-unclosed-literal": { en: "The array literal is not closed.", ja: "array literalが閉じられていません。" },
  "diagnostic.array-parameter-default": { en: "Array Module parameters cannot have defaults.", ja: "array 型 Module parameter に default は指定できません。" },
  "diagnostic.array-invalid-reference": { en: "Invalid array alias reference.", ja: "array alias の参照が不正です。" },
  "diagnostic.array-reference-forward": { en: "Array '{reference}' is declared later.", ja: "array「{reference}」はこの位置より後で宣言されています。" },
  "diagnostic.array-reference-ambiguous": { en: "Array reference '{reference}' is ambiguous.", ja: "array 参照が曖昧です: {reference}" },
  "diagnostic.array-reference-undefined": { en: "Array reference '{reference}' could not be resolved.", ja: "未解決の array 参照です: {reference}" },
  "diagnostic.array-reference-invalidTraversal": { en: "Array reference traversal '{reference}' is invalid.", ja: "array 参照「{reference}」の traversal が不正です。" },
  "diagnostic.array-reference-not-array": { en: "Reference '{reference}' is not an array compatible with this collection type.", ja: "参照先「{reference}」はこの collection 型と互換性のある array ではありません。" },
  "diagnostic.array-member-forward": { en: "Array member '{member}' is declared later.", ja: "array member「{member}」はこの位置より後で宣言されています。" },
  "diagnostic.array-member-ambiguous": { en: "Array member reference '{member}' is ambiguous.", ja: "array member 参照が曖昧です: {member}" },
  "diagnostic.array-member-undefined": { en: "Array member '{member}' could not be resolved.", ja: "未解決の array member です: {member}" },
  "diagnostic.array-member-invalidTraversal": { en: "Array member traversal '{member}' is invalid.", ja: "array member「{member}」の traversal が不正です。" },
  "diagnostic.array-member-invalid-type": { en: "The type of reference '{member}' could not be resolved.", ja: "参照先「{member}」の型を解決できません。" },
  "diagnostic.array-member-not-value": { en: "Reference '{member}' cannot be used as an array member value.", ja: "参照先「{member}」は array member に使用できる value ではありません。" },
  "diagnostic.array-member-type-mismatch": { en: "Array member '{member}' does not match the declared element type.", ja: "array member「{member}」の型が宣言型と一致しません。" },
  "diagnostic.nested-array-member": { en: "Array literals cannot contain nested arrays.", ja: "配列を array literal member として入れ子にすることはできません。" },
  "diagnostic.array-argument-invalid": { en: "Array parameter '{parameter}' requires a compatible whole-value collection reference.", ja: "array parameter「{parameter}」には compatible な whole-value collection reference が必要です。" },
  "diagnostic.array-argument-type-mismatch": { en: "Array argument '{argument}' does not match parameter '{parameter}'.", ja: "array argument「{argument}」の型が parameter「{parameter}」と一致しません。" },
  "diagnostic.array-assignability-mismatch": { en: "Array type '{actual}' is not assignable to '{expected}'.", ja: "array型「{actual}」を「{expected}」に代入できません。" },
  "diagnostic.array-value-for-unsupported": { en: "This collection does not support value-for.", ja: "この collection では value-for を使用できません。" },
  "diagnostic.geometry-array-expected-array": { en: "The expected geometry-array type is invalid.", ja: "geometry array の期待型が不正です。" },
  "diagnostic.coalesce-left-not-optional": { en: "The left operand of ?? must have an optional type.", ja: "?? の左辺は optional 型である必要があります。" },
  "diagnostic.coalesce-type-mismatch": { en: "The ?? record operands must be the same optional nominal record type and its underlying record type.", ja: "?? の record operands は optional な同一 nominal record 型と、その underlying record 型である必要があります。" },
  "diagnostic.value-if-missing-else": { en: "A value-if without else requires an optional result type.", ja: "else を省略できる value-if の結果型は optional である必要があります。" },
  "diagnostic.geometry-array-value-for-source-invalid": { en: "Value-for source '{source}' must resolve to a whole-value geometry collection.", ja: "value-for source「{source}」には解決可能な whole-value geometry collection reference が必要です。" },
  "diagnostic.geometry-array-value-for-source-forward": { en: "Geometry collection value-for source '{source}' is declared later.", ja: "value-for source「{source}」はこの位置より後で宣言されています。" },
  "diagnostic.array-value-for-invalid": { en: "The collection value-for expression is invalid.", ja: "collectionのvalue-for式が不正です。" },
  "diagnostic.array-value-for-source-invalid": { en: "The value-for source must be a visible whole-value collection.", ja: "value-forのsourceには可視のwhole-value collectionが必要です。" },
  "diagnostic.array-value-for-source-forward": { en: "The value-for source is declared later and cannot be referenced yet.", ja: "value-forのsourceはこの位置より後で宣言されているため、まだ参照できません。" },
  "diagnostic.array-value-for-source-unsupported": { en: "This value-for slice supports only scalar and choice collections.", ja: "このvalue-for Sliceが対応するsource/resultはscalarまたはchoice collectionのみです。" },
  "diagnostic.array-value-for-body-invalid": { en: "The value-for body is invalid.", ja: "value-for bodyが不正です。" },
  "diagnostic.array-value-for-body-reference-invalid": { en: "A value-for body reference could not be resolved.", ja: "value-for bodyの参照を解決できません。" },
  "diagnostic.geometry-array-value-for-unsupported": { en: "Geometry arrays do not support scalar value-for expressions.", ja: "geometry arrayではscalar value-for式を使用できません。" },
  "diagnostic.record-field-default-unsupported": { en: "Record fields cannot use defaults in nui 1.", ja: "record fieldのdefaultはnui 1では使用できません。" },
  "diagnostic.record-field-duplicate": { en: "Record field '{name}' is duplicated.", ja: "record field「{name}」が重複しています。" },
  "diagnostic.record-field-invalid-shape": { en: "Record fields must use the form 'name: type'.", ja: "record fieldは「名前: 型」の形式で指定してください。" },
  "diagnostic.record-field-invalid-type": { en: "Record field type '{type}' is invalid.", ja: "record fieldの型「{type}」が不正です。" },
  "diagnostic.record-field-missing-type": { en: "Record fields require an immutable value type annotation.", ja: "record fieldにはimmutable value型注釈が必要です。" },
  "diagnostic.record-field-optional-unsupported": { en: "Optional record fields are not supported in nui 1.", ja: "optional record fieldはnui 1では使用できません。" },
  "diagnostic.record-invalid-name": { en: "A record definition requires a bare identifier name.", ja: "record definitionには裸の識別子名が必要です。" },
  "diagnostic.record-missing-field-list": { en: "A record definition requires a field list.", ja: "record definitionにはfield listが必要です。" },
  "diagnostic.record-trailing-token": { en: "Unexpected token after the record field list.", ja: "record definitionの後に余分なtokenがあります。" },
  "diagnostic.record-unclosed-field-list": { en: "The record field list is not closed.", ja: "record field listが閉じられていません。" },
  "diagnostic.record-field-invalid-traversal": { en: "Record field traversal '{target}' is invalid.", ja: "record field「{target}」のtraversalが不正です。" },
  "diagnostic.record-field-unavailable": { en: "Record field '{target}' is unavailable here.", ja: "record field「{target}」はこの位置では利用できません。" },
  "diagnostic.record-field-unknown": { en: "Record '{record}' has no field '{field}'.", ja: "record「{record}」にfield「{field}」はありません。" },
  "diagnostic.record-constructor-duplicate-field": { en: "Record constructor field '{field}' is duplicated.", ja: "record constructorのfield「{field}」が重複しています。" },
  "diagnostic.record-constructor-missing-field": { en: "Required field '{field}' is missing from record constructor '{record}'.", ja: "record constructor「{record}」に必須field「{field}」がありません。" },
  "diagnostic.record-constructor-positional-argument": { en: "Record constructors accept named arguments only.", ja: "record constructorの引数はnamed-onlyです。" },
  "diagnostic.record-constructor-unknown-field": { en: "Record '{record}' has no constructor field '{field}'.", ja: "record「{record}」にconstructor field「{field}」はありません。" },
  "diagnostic.record-value-ambiguous": { en: "Record value reference '{name}' is ambiguous.", ja: "record value参照「{name}」が曖昧です。" },
  "diagnostic.record-value-forward-reference": { en: "Record value '{name}' is declared later.", ja: "record value「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.import-root-unaddressable": { en: "The relative import path '{path}' cannot be resolved from the importer.", ja: "import元から相対path「{path}」を解決できません。" },
  "diagnostic.import-missing": { en: "The imported file '{path}' was not found.", ja: "import先「{path}」が見つかりません。" },
  "diagnostic.import-unreadable": { en: "The imported file '{path}' could not be read.", ja: "import先「{path}」を読み込めません。" },
  "diagnostic.import-load-stale": { en: "The imported file '{path}' load is stale.", ja: "import先「{path}」の読み込み結果がstaleです。" },
  "diagnostic.import-load-canceled": { en: "Loading the imported file '{path}' was canceled.", ja: "import先「{path}」の読み込みがcancelされました。" },
  "diagnostic.import-invalid-source": { en: "The imported file '{path}' is not valid nui 1 source.", ja: "import先「{path}」は有効なnui 1 sourceではありません。" },
  "diagnostic.import-invalid-dependency": { en: "The imported dependency graph for '{path}' is invalid.", ja: "import先「{path}」のdependency graphが無効です。" },
  "diagnostic.import-cycle": { en: "An import cycle was detected: {chain}.", ja: "import cycleを検出しました: {chain}。" },
  "diagnostic.invalid-import-syntax": { en: "Invalid import syntax.", ja: "import文の形式が不正です。" },
  "diagnostic.invalid-import-path": { en: "The import path is invalid.", ja: "import pathが不正です。" },
  "diagnostic.invalid-import-alias": { en: "The import alias is invalid.", ja: "import aliasが不正です。" },
  "diagnostic.missing-import-alias": { en: "An import alias is required.", ja: "import aliasが必要です。" },
  "diagnostic.invalid-file-reexport": { en: "Invalid file re-export.", ja: "file re-exportが不正です。" },
  "diagnostic.file-reexport-top-level-only": { en: "File re-exports are allowed only at the document top level.", ja: "file re-exportは文書のトップレベルにのみ指定できます。" },
  "diagnostic.module-recursion": { en: "A Module recursion cycle was detected for '{name}'.", ja: "「{name}」のModule recursion cycleを検出しました。" },
  "diagnostic.module-semantic-invalid": { en: "The Module semantics are invalid.", ja: "Moduleの意味解析が不正です。" },
  "diagnostic.module-duplicate-export": { en: "The Module export name '{name}' is duplicated.", ja: "Module export名「{name}」が重複しています。" },
  "diagnostic.module-invalid-export": { en: "The Module export is invalid.", ja: "Module exportが不正です。" },
  "diagnostic.module-forbidden-body-statement": { en: "The '{statement}' statement is not allowed in a Module body.", ja: "「{statement}」文はModule bodyでは使用できません。" },
  "diagnostic.module-optional-value-required": { en: "Resolve optional Module value '{name}' before using it.", ja: "optional Module value「{name}」を解決してから使用してください。" },
  "diagnostic.module-geometry-parameter-mutation": { en: "Geometry Module parameter '{target}' cannot be mutated here.", ja: "geometry Module parameter「{target}」はここでは変更できません。" },
  "diagnostic.module-geometry-type-mismatch": { en: "Module geometry reference '{target}' has the wrong type.", ja: "Module geometry参照「{target}」の型が一致しません。" },
  "diagnostic.duplicate-public-export": { en: "The public export name '{name}' is duplicated.", ja: "公開export名「{name}」が重複しています。" },
  "diagnostic.invalid-reexport-target": { en: "The re-export target '{importAlias}' could not be resolved safely.", ja: "re-export元「{importAlias}」を安全に解決できません。" },
  "diagnostic.private-reexport-target": { en: "The target '{importAlias}::{exportedName}' is private and cannot be re-exported.", ja: "「{importAlias}::{exportedName}」は公開されていないためre-exportできません。" },
  "diagnostic.missing-reexport-target": { en: "The public re-export target '{importAlias}::{exportedName}' does not exist.", ja: "「{importAlias}::{exportedName}」に対応する公開宣言がありません。" },
  "diagnostic.builtin-geometry-argument-invalid": { en: "The geometry argument is invalid.", ja: "geometry引数が不正です。" },
  "diagnostic.builtin-geometry-argument-invalid-reference": { en: "Geometry reference '{reference}' is invalid.", ja: "geometry参照「{reference}」が不正です。" },
  "diagnostic.builtin-geometry-argument-invalid-direct": { en: "Geometry argument to '{function}' must be a direct {expected} reference.", ja: "「{function}」のgeometry引数は{expected}の直接参照である必要があります。" },
  "diagnostic.builtin-geometry-argument-invalid-property": { en: "Geometry property '{reference}' cannot be used as a {expected} argument.", ja: "geometry property「{reference}」は{expected}引数として使用できません。" },
  "diagnostic.builtin-geometry-type-mismatch": { en: "The geometry argument has the wrong type (expected {expected}, got {actual}).", ja: "geometry引数の型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.evaluation-failed": { en: "Evaluation failed.", ja: "評価に失敗しました。" },
  "diagnostic.runtime.poisoned-binding": { en: "Evaluation failed and this binding is disabled.", ja: "評価に失敗し、このbindingは無効化されています。" },
  "diagnostic.runtime.evaluation-binding-unavailable": { en: "The referenced binding is unavailable.", ja: "参照先のbindingを解決できません。" },
  "diagnostic.runtime.evaluation-runtime-value-type-mismatch": { en: "The runtime value type does not match its declaration.", ja: "実行時の値の型が宣言と一致しません。" },
  "diagnostic.runtime.evaluation-binding-cycle-guard": { en: "A runtime binding cycle was detected.", ja: "実行時のbinding循環参照が検出されました。" },
  "diagnostic.runtime.evaluation-divide-by-zero": { en: "Division by zero occurred.", ja: "0での除算が発生しました。" },
  "diagnostic.runtime.evaluation-remainder-by-zero": { en: "Remainder by zero occurred.", ja: "0での剰余が発生しました。" },
  "diagnostic.runtime.evaluation-invalid-builtin-argument": { en: "A builtin function argument is invalid.", ja: "組み込み関数の引数が不正です。" },
  "diagnostic.runtime.evaluation-geometry-builtin-unavailable": { en: "The geometry argument is unavailable.", ja: "組み込み関数のgeometry引数を評価できません。" },
  "diagnostic.runtime.evaluation-geometry-builtin-disabled.target": { en: "'{target}' is disabled and cannot be used as a geometry argument. Enable '{base}' or choose another reference.", ja: "「{target}」は評価OFFのためgeometry引数として利用できません。「{base}」を評価ONにするか、参照先を変更してください。" },
  "diagnostic.runtime.evaluation-geometry-builtin-disabled": { en: "A geometry argument is disabled.", ja: "組み込み関数のgeometry引数がdisabledのため利用できません。" },
  "diagnostic.runtime.evaluation-zero-length-line": { en: "A zero-length line cannot be used here.", ja: "長さ0のlineはここでは使用できません。" },
  "diagnostic.runtime.evaluation-sqrt-negative-input": { en: "The sqrt argument must be at least zero.", ja: "sqrtの引数は0以上である必要があります。" },
  "diagnostic.runtime.evaluation-round-to-non-positive-step": { en: "The roundTo step must be greater than zero.", ja: "roundToのstepは0より大きい必要があります。" },
  "diagnostic.runtime.evaluation-is-close-negative-tolerance": { en: "The isClose tolerance must be at least zero.", ja: "isCloseのtoleranceは0以上である必要があります。" },
  "diagnostic.runtime.evaluation-tan-odd-multiple-of-90": { en: "tan is undefined at 90° + 180° × n.", ja: "tanは90°+180°×nでは定義できません。" },
  "diagnostic.runtime.evaluation-asin-out-of-range": { en: "The asin argument must be between -1 and 1.", ja: "asinの引数は-1以上1以下である必要があります。" },
  "diagnostic.runtime.evaluation-acos-out-of-range": { en: "The acos argument must be between -1 and 1.", ja: "acosの引数は-1以上1以下である必要があります。" },
  "diagnostic.runtime.evaluation-non-finite-result": { en: "The calculation produced an invalid number.", ja: "計算結果が数値として不正です。" },
  "diagnostic.runtime.evaluation-static-type-null": { en: "The type could not be determined.", ja: "型を確定できませんでした。" },
  "diagnostic.runtime.evaluation-numeric-adapter-failure": { en: "Numeric evaluation failed.", ja: "数値の評価に失敗しました。" },
  "diagnostic.runtime.evaluation-geometry-property-unavailable": { en: "The element property is unavailable at this position.", ja: "要素プロパティはこの位置では評価できません。" },
  "diagnostic.required-value-missing": { en: "A required value is missing.", ja: "必須の値がありません。" },
  "diagnostic.revalidation-failed": { en: "The source changed before this diagnostic could be applied.", ja: "この診断を適用する前にSourceが変更されました。" },
  "diagnostic.missing-declared-type": { en: "A type annotation is required.", ja: "型注釈が必要です。" },
  "diagnostic.invalid-number-type-options": { en: "The number type options are invalid.", ja: "number型の設定が不正です。" },
  "diagnostic.geometry-property-invalid": { en: "Geometry property reference '{target}' is invalid.", ja: "geometry property参照「{target}」が不正です。" },
  "diagnostic.const-assignment": { en: "Const binding '{name}' cannot be assigned.", ja: "const binding「{name}」には代入できません。" },
  "diagnostic.property-binding-not-supported": { en: "This property does not support a binding.", ja: "このpropertyはbindingをサポートしていません。" },
  "diagnostic.property-binding-unresolved": { en: "Property binding reference '{name}' could not be resolved.", ja: "property bindingの参照「{name}」を解決できません。" },
  "diagnostic.property-binding-invalid": { en: "Property binding reference '{name}' is invalid.", ja: "property bindingの参照「{name}」が不正です。" },
  "diagnostic.property-binding-type-mismatch": { en: "Property binding '{name}' has the wrong type (expected {expected}, got {actual}).", ja: "property binding「{name}」の型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.conditional-group-condition-unresolved": { en: "Conditional group condition reference '{name}' could not be resolved.", ja: "条件グループのconditionの参照「{name}」を解決できません。" },
  "diagnostic.conditional-group-condition-invalid": { en: "Conditional group condition reference '{name}' is invalid.", ja: "条件グループのconditionの参照「{name}」が不正です。" },
  "diagnostic.conditional-group-condition-type-mismatch": { en: "The conditional group condition must be boolean.", ja: "条件グループのconditionはbooleanである必要があります。" },
  "diagnostic.numeric-binding-unresolved": { en: "Numeric binding reference '{name}' could not be resolved.", ja: "数値bindingの参照「{name}」を解決できません。" },
  "diagnostic.numeric-binding-type-mismatch": { en: "Numeric binding has the wrong type (expected {expected}, got {actual}).", ja: "数値bindingの型が一致しません（期待: {expected}、実際: {actual}）。" },
  "diagnostic.numeric-binding-mapping": { en: "The numeric binding mapping is invalid.", ja: "数値bindingの対応付けが不正です。" },
  "diagnostic.numeric-binding-iteration-reference": { en: "Iteration reference '{name}' is invalid here.", ja: "この位置のiteration参照「{name}」が不正です。" },
  "diagnostic.text-template-hole-unresolved": { en: "Text template reference '{reference}' could not be resolved.", ja: "text templateの参照「{reference}」を解決できません。" },
  "diagnostic.text-template-hole-invalid": { en: "Text template reference '{reference}' is invalid.", ja: "text templateの参照「{reference}」が不正です。" },
  "diagnostic.interpolation-type-mismatch": { en: "The interpolated value has the wrong type (got {actual}).", ja: "interpolationされた値の型が一致しません（実際: {actual}）。" },
  "diagnostic.invalid-literal-token": { en: "Invalid literal.", ja: "literalが不正です。" },
  "diagnostic.invalid-string-escape": { en: "Invalid string escape.", ja: "文字列escapeが不正です。" },
  "diagnostic.unterminated-string": { en: "A string literal is missing its closing quote.", ja: "string literalの閉じ引用符がありません。" },
  "diagnostic.physical-newline-in-string": { en: "String literals cannot contain a physical newline; use \\n or \\r.", ja: "string literalには物理的な改行を含められません。\\n または \\r を使用してください。" },
  "diagnostic.missing-operand": { en: "An expression operand is missing.", ja: "式のoperandがありません。" },
  "diagnostic.unterminated-group": { en: "The expression group is not closed.", ja: "式のgroupが閉じられていません。" },
  "diagnostic.unterminated-index": { en: "A collection index is missing its closing ']'.", ja: "閉じ括弧 ']' がありません。" },
  "diagnostic.empty-index": { en: "A collection index requires an expression.", ja: "collection index の式が必要です。" },
  "diagnostic.trailing-token": { en: "Unexpected trailing token.", ja: "予期しない末尾tokenです。" },
  "diagnostic.expression-depth-exceeded": { en: "The expression is too deeply nested.", ja: "式の入れ子が深すぎます。" },
  "diagnostic.chained-comparison-not-supported": { en: "Chained comparisons are not supported.", ja: "比較演算子の連鎖はサポートされていません。" },
  "diagnostic.geometry-property-in-typed-expression": { en: "Geometry properties cannot be used in this expression.", ja: "この式ではgeometry propertyを使用できません。" },
  "diagnostic.unclosed-call": { en: "The call is not closed.", ja: "callが閉じられていません。" },
  "diagnostic.missing-category": { en: "The statement must start with a category.", ja: "文は category から始めてください。" },
  "diagnostic.unknown-category": { en: "Unknown category '{category}'.", ja: "未知の category「{category}」です。" },
  "diagnostic.bare-construction-not-call": { en: "Construction '{construction}' cannot be declared under category '{category}' in this form.", ja: "「{construction}」はcategory「{category}」ではこの形式で宣言できません。" },
  "diagnostic.construction-positional-argument-not-accepted": { en: "Construction '{construction}' in category '{category}' does not accept positional arguments.", ja: "category「{category}」のconstruction「{construction}」は位置引数を受け付けません。" },
  "diagnostic.construction-positional-argument-duplicate": { en: "Positional argument '{argument}' is duplicated.", ja: "位置引数「{argument}」が重複しています。" },
  "diagnostic.construction-positional-argument-named": { en: "Positional argument '{argument}' cannot be supplied by name.", ja: "位置引数「{argument}」は名前付き引数として指定できません。" },
  "diagnostic.construction-argument-duplicate": { en: "Argument '{argument}' is duplicated.", ja: "引数「{argument}」が重複しています。" },
  "diagnostic.missing-construction-argument": { en: "Construction '{construction}' requires argument '{argument}'.", ja: "construction「{construction}」には必須引数「{argument}」が必要です。" },
  "diagnostic.exclusive-construction-arguments": { en: "Arguments '{arguments}' cannot be supplied together.", ja: "引数「{arguments}」は同時に指定できません。" },
  "diagnostic.missing-construction": { en: "A construction is required.", ja: "construction が必要です。" },
  "diagnostic.missing-construction-call-open": { en: "A construction must be followed by '('.", ja: "construction の後には「(」が必要です。" },
  "diagnostic.style-reference-name-required": { en: "A style reference requires a named geometry or group.", ja: "style参照は名前付きのgeometry / groupにのみ指定できます。" },
  "diagnostic.style-reference-list-unclosed": { en: "The style reference list is not closed.", ja: "style参照リストの「[」が閉じられていません。" },
  "diagnostic.style-reference-list-trailing-token": { en: "Unexpected token after the style reference list.", ja: "style参照リストの後に余分なトークンがあります。" },
  "diagnostic.style-reference-named-argument": { en: "Style reference lists accept names only.", ja: "style参照リストには名前だけを書いてください。" },
  "diagnostic.style-reference-invalid-name": { en: "The style reference name is empty or invalid.", ja: "style参照名が空、または不正です。" },
  "diagnostic.style-reference-name-unquoted-whitespace": { en: "Style reference names containing spaces must be quoted.", ja: "style参照名に空白を含める場合は引用符で囲んでください。" },
  "diagnostic.trailing-token-after-call": { en: "Unexpected token after the call.", ja: "呼び出しの「)」の後に余分なトークンがあります。" },
  "diagnostic.trailing-token-after-block": { en: "Unexpected token after the block opener.", ja: "「{」の後に余分なトークンがあります。" },
  "diagnostic.missing-block": { en: "The {category} statement requires a block.", ja: "{category} にはブロックが必要です。" },
  "diagnostic.style-missing-name": { en: "A style definition requires a name.", ja: "style には名前が必要です。" },
  "diagnostic.style-invalid-name": { en: "The style name is invalid. Quote names containing spaces or syntax punctuation.", ja: "style の名前が不正です。空白や構文記号を含める場合は引用符で囲んでください。" },
  "diagnostic.style-property-missing-trailing-comma": { en: "Style properties require a trailing comma.", ja: "style のプロパティには末尾の「,」が必要です。" },
  "diagnostic.style-property-multiple-per-line": { en: "Only one style property may be specified on each line.", ja: "style ブロックでは1行に1つのプロパティだけ指定できます。" },
  "diagnostic.style-property-missing-value": { en: "Style property '{property}' has no value.", ja: "style プロパティ「{property}」の値がありません。" },
  "diagnostic.style-width-invalid": { en: "Style width must be a positive finite decimal px literal (for example, 1.5px).", ja: "style の width は正の有限な10進数pxリテラルで指定してください(例: 1.5px)。" },
  "diagnostic.style-line-type-invalid": { en: "Style lineType must be solid, dashed, or dotted.", ja: "style の lineType は solid / dashed / dotted のいずれかで指定してください。" },
  "diagnostic.style-visible-invalid": { en: "Style visible must be true or false.", ja: "style の visible は true / false のいずれかで指定してください。" },
  "diagnostic.style-color-fixed-invalid": { en: "A fixed style color must use the form #RRGGBB.", ja: "style の color 固定色は #RRGGBB の形式で指定してください。" },
  "diagnostic.style-color-invalid": { en: "Style color must be foreground, muted, accent, info, warning, error, or #RRGGBB.", ja: "style の color は foreground / muted / accent / info / warning / error または #RRGGBB で指定してください。" },
  "diagnostic.style-fill-invalid": { en: "Style fill must be foreground, muted, accent, info, warning, error, #RRGGBB, or none.", ja: "style の fill は foreground / muted / accent / info / warning / error、#RRGGBB、または none で指定してください。" },
  "diagnostic.style-fill-opacity-invalid-number": { en: "Style fillOpacity must be a finite number.", ja: "style の fillOpacity は有限な数値で指定してください。" },
  "diagnostic.style-fill-opacity-out-of-range": { en: "Style fillOpacity must be between 0 and 1 inclusive.", ja: "style の fillOpacity は 0 以上 1 以下で指定してください。" },
  "diagnostic.style-profile-reference-invalid": { en: "Style for reference '{reference}' must be an @profile reference.", ja: "style の for 参照「{reference}」が不正です。@profile 参照で指定してください。" },
  "diagnostic.style-profile-reference-property-not-allowed": { en: "A style for reference cannot specify a property.", ja: "style の for 参照には property を指定できません。" },
  "diagnostic.profile-missing-name": { en: "A profile definition requires a name.", ja: "profile には名前が必要です。" },
  "diagnostic.profile-invalid-name": { en: "The profile name is invalid. Quote names containing spaces or syntax punctuation.", ja: "profile の名前が不正です。空白や構文記号を含める場合は引用符で囲んでください。" },
  "diagnostic.missing-statement-keyword": { en: "A statement must begin with a keyword.", ja: "文はキーワードから始めてください。" },
  "diagnostic.invalid-else-placement": { en: "`else` is allowed only immediately after the then branch of an if block.", ja: "「} else {」は if ブロックの then 部の直後にのみ書けます。" },
  "diagnostic.unmatched-block-end": { en: "This closing brace has no matching block opener.", ja: "対応するブロックの開きがない「}」です。" },
  "diagnostic.statement-top-level-only": { en: "{keyword} statements are allowed only at the document top level.", ja: "{keyword} は文書のトップレベルにのみ書けます。" },
  "diagnostic.profile-top-level-only": { en: "Profile definitions are allowed only at the document top level.", ja: "profile 定義は文書のトップレベルにのみ書けます。" },
  "diagnostic.style-property-outside-style": { en: "Style properties are allowed only inside a style or style for @profile block.", ja: "style プロパティは style または for @profile ブロック内にのみ書けます。" },
  "diagnostic.style-profile-outside-style": { en: "A style for @profile block is allowed only inside a style block.", ja: "style の for @profile ブロックは style ブロック内にのみ書けます。" },
  "diagnostic.style-nested-definition": { en: "A style definition cannot be nested inside another block.", ja: "style 定義を別のブロック内にネストできません。" },
  "diagnostic.style-block-invalid-statement": { en: "A style block may contain only visible, width, lineType, color, fill, fillOpacity, or for @profile.", ja: "style ブロック内には visible / width / lineType / color / fill / fillOpacity または for @profile だけを書けます。" },
  "diagnostic.layout-block-invalid-statement": { en: "A layout block may contain only place statements.", ja: "layout ブロック内には place のみ書けます。" },
  "diagnostic.place-outside-layout": { en: "Place statements are allowed only inside a layout block.", ja: "place は layout ブロック内にのみ書けます。" },
  "diagnostic.statement-block-not-allowed": { en: "This statement cannot open a block.", ja: "この文はブロックを開けません。" },
  "diagnostic.unclosed-block": { en: "The block is not closed. Close it with '}'.", ja: "ブロックが閉じられていません。「}」で閉じてください。" },
  "diagnostic.style-top-level-only": { en: "Style definitions are allowed only at the document top level.", ja: "style 定義は文書のトップレベルにのみ書けます。" },
  "diagnostic.style-duplicate-name": { en: "Style name '{name}' is duplicated (also declared on line {previousLine}).", ja: "style 名「{name}」が重複しています（行 {previousLine} と重複）。" },
  "diagnostic.style-duplicate-property": { en: "Style property '{property}' may be specified only once.", ja: "style の {property} プロパティは1つだけ指定できます。" },
  "diagnostic.style-unknown-property": { en: "Style has an unknown property '{property}'.", ja: "style に未知のプロパティ「{property}」があります。" },
  "diagnostic.style-profile-duplicate-property": { en: "Style for @{profile} property '{property}' may be specified only once.", ja: "style の for @{profile} 内の {property} プロパティは1つだけ指定できます。" },
  "diagnostic.style-profile-unknown-property": { en: "Style for @{profile} has an unknown property '{property}'.", ja: "style の for @{profile} に未知のプロパティ「{property}」があります。" },
  "diagnostic.style-profile-empty": { en: "Style for @{profile} requires at least one property.", ja: "style の for @{profile} にはプロパティが1つ以上必要です。" },
  "diagnostic.style-empty": { en: "A style requires at least one property or profile block.", ja: "style には visible / width / lineType / color / fill / fillOpacity または for @profile が1つ以上必要です。" },
  "diagnostic.duplicate-element-name": { en: "Element name '{name}' is duplicated in the same scope (also declared on line {previousLine}).", ja: "同名の要素が同じスコープにあります: {name}(行 {previousLine} と重複)" },
  "diagnostic.unterminated-block-comment": { en: "The block comment is not closed. Close it with '*/'.", ja: "ブロックコメントが閉じられていません。「*/」で閉じてください。" },
  "diagnostic.next-outside-for": { en: "next is allowed only inside a statement-for carry scope.", ja: "next は statement-for の carry scope 内でのみ使用できます。" },
  "diagnostic.unclosed-range-call": { en: "The range call is not closed.", ja: "range 呼び出しの「(」が閉じられていません。" },
  "diagnostic.container-header-equals-not-allowed": { en: "The {category} header cannot use '='.", ja: "{category} ヘッダでは「=」を使えません。" },
  "diagnostic.invalid-if-header": { en: "The if header must use the form `if (@condition) { ... }`.", ja: "if は `if (@condition) { ... }` の形式で書いてください。" },
  "diagnostic.bare-call-shape": { en: "The {category} call must use the form `{category}(arguments…)`.", ja: "{category} は「{category}(引数…)」の形式で書いてください。" },
  "diagnostic.missing-container-call-arguments": { en: "The {category} statement requires arguments in parentheses.", ja: "{category} には括弧内の引数が必要です。" },
  "diagnostic.call-block-not-allowed": { en: "The {category} call cannot open a block.", ja: "{category} の呼び出しはブロックを開けません。" },
  "diagnostic.missing-transformation-call-open": { en: "Transformation '{operation}' requires an argument list.", ja: "{operation} には引数括弧が必要です。" },
  "diagnostic.missing-element-equals": { en: "An element statement requires '='.", ja: "要素文には「=」が必要です。" },
  "diagnostic.missing-element-construction": { en: "A construction is required after '='.", ja: "「=」の後に construction が必要です。" },
  "diagnostic.unsupported-use": { en: "The use statement is reserved but not implemented.", ja: "use は予約済みですが、まだ実装されていません。" },
  "diagnostic.invalid-carry": { en: "The carry declaration is invalid.", ja: "carry には名前が必要です。" },
  "diagnostic.invalid-for-header": { en: "The for header is invalid.", ja: "for ヘッダの形式が不正です。" },
  "diagnostic.missing-carry-type": { en: "A carry declaration requires a non-empty type annotation.", ja: "carry には型注釈が必要です。" },
  "diagnostic.missing-carry-initializer": { en: "A carry declaration requires an initializer.", ja: "carry には初期化式が必要です。" },
  "diagnostic.missing-for-source": { en: "A for statement requires a range(...) or collection source.", ja: "for には range(...) または collection source が必要です。" },
  "diagnostic.malformed-transformation-target": { en: "The transformation target syntax is invalid.", ja: "transformation targetの形式が不正です。" },
  "diagnostic.unresolved-transformation-target": { en: "The transformation target could not be resolved as a geometry.", ja: "transformation target を geometry として解決できません。" },
  "diagnostic.invalid-final-transformation-target": { en: "`final` cannot be used as a transformation target.", ja: "`final` は transformation target に指定できません。" },
  "diagnostic.transformation-target-kind-incompatible": { en: "The transformation target is incompatible with this operation.", ja: "transformation target はこの operation と互換性がありません。" },
  "diagnostic.generated-occurrence-unavailable": { en: "The requested generated occurrence is unavailable.", ja: "指定された generated occurrence は利用できません。" },
  "diagnostic.unresolved-transformation-stage": { en: "The transformation stage is not available at this point.", ja: "transformation stage はこの位置では利用できません。" },
  "diagnostic.reserved-transformation-stage-name": { en: "The transformation stage name is reserved.", ja: "transformation stage name は予約されています。" },
  "diagnostic.transformation-stage-property-collision": { en: "The transformation stage name conflicts with a geometry property.", ja: "transformation stage name が geometry property と衝突しています。" },
  "diagnostic.duplicate-transformation-stage": { en: "A transformation stage with this name already exists in this recipe branch.", ja: "この recipe branch には同じ名前の transformation stage があります。" },
  "diagnostic.invalid-transformation-enabled": { en: "Transformation enabled must be true or false.", ja: "transformation の enabled は true / false で指定してください。" },
  "diagnostic.invalid-module-instance-gate": { en: "Module instance option '{option}' must be true, false, or a shared boolean reference.", ja: "{option} は true/false または共有 boolean 参照で指定してください。" },
  "diagnostic.module-parameter-invalid-shape": { en: "A Module parameter must use the form `name: type`.", ja: "module parameter は `名前: 型` の形式で指定してください。" },
  "diagnostic.module-parameter-missing-type": { en: "A Module parameter requires a type annotation.", ja: "module parameter には型注釈が必要です。" },
  "diagnostic.module-parameter-missing-default": { en: "A Module parameter default requires a value after '='.", ja: "module parameter の default には `=` の後に値が必要です。" },
  "diagnostic.module-argument-not-named": { en: "Module arguments must be named; the simple `@name` shorthand is also supported.", ja: "module argument は名前付き引数で指定してください。単純な `@name` shorthand も使用できます。" },
  "diagnostic.module-instance-option-not-named": { en: "Module instance options must be named.", ja: "module instance option は名前付き引数で指定してください。" },
  "diagnostic.module-instance-unknown-option": { en: "Module instance option '{option}' is not supported. Allowed options: {candidates}.", ja: "module instance option「{option}」はありません。使用できるoption: {candidates}。" },
  "diagnostic.module-instance-duplicate-option": { en: "Module instance option '{option}' is duplicated.", ja: "引数「{option}」が重複しています。" },
  "diagnostic.module-trailing-token-after-block": { en: "Unexpected token after the Module block opener.", ja: "「{」の後に余分なトークンがあります。" },
  "diagnostic.module-definition-missing-name": { en: "A Module definition requires a name.", ja: "module definition には名前が必要です。" },
  "diagnostic.module-definition-missing-parameter-list": { en: "A Module definition requires a parameter list.", ja: "module definition には parameter list の「(」が必要です。" },
  "diagnostic.module-parameter-list-unclosed": { en: "The Module parameter list is not closed.", ja: "module parameter list の「(」が閉じられていません。" },
  "diagnostic.module-definition-missing-block": { en: "A Module definition requires a block.", ja: "module definition にはブロックが必要です。" },
  "diagnostic.module-instance-missing-name": { en: "A Module instance requires an instance name.", ja: "module instance にはインスタンス名が必要です。" },
  "diagnostic.module-instance-missing-callee": { en: "A Module instance requires a Module name to call.", ja: "module instance には呼び出すmodule名が必要です。" },
  "diagnostic.module-instance-missing-argument-list": { en: "A Module instance requires an argument list.", ja: "module instance には argument list の「(」が必要です。" },
  "diagnostic.module-argument-list-unclosed": { en: "The Module argument list is not closed.", ja: "module argument list の「(」が閉じられていません。" },
  "diagnostic.module-instance-trailing-token": { en: "Unexpected token after the Module instance call.", ja: "module instance の「)」の後に余分なトークンがあります。" },
  "diagnostic.missing-declaration-name": { en: "A declaration requires a name.", ja: "const には名前が必要です。" },
  "diagnostic.empty-declared-type": { en: "The type annotation cannot be empty.", ja: "const には型注釈(: 型)が必要です。" },
  "diagnostic.missing-declaration-initializer": { en: "A declaration requires an initializer.", ja: "const には初期化式(= 値)が必要です。" },
  "diagnostic.empty-declaration-initializer": { en: "An initializer requires a value after '='.", ja: "初期化式には「=」の後に値が必要です。" },
  "diagnostic.missing-next-target": { en: "The next statement requires a carry target.", ja: "next には対象の carry 名が必要です。" },
  "diagnostic.missing-next-expression": { en: "The next statement requires a `name = expression` value.", ja: "next には `name = expression` の式が必要です。" },
  "diagnostic.unclosed-choice-type": { en: "The choice type is not closed.", ja: "choice の「(」が閉じられていません。" },
  "diagnostic.trailing-token-after-choice-type": { en: "Unexpected token after the choice type.", ja: "choice(...) の後に余分なトークンがあります。" },
  "diagnostic.reserved-none-choice-option": { en: "The reserved word 'none' cannot be used as a choice option.", ja: "予約語 none は choice option に使用できません。" },
  "diagnostic.repeated-optional-type": { en: "An optional type marker may be specified only once.", ja: "optional 型の ? は1つだけ指定できます。T?? は使用できません。" },
  "diagnostic.nested-array-type": { en: "Only one array dimension is supported.", ja: "配列は1次元のみ対応しています。T[][] は使用できません。" },
  "diagnostic.invalid-export-statement": { en: "An export must be followed by a geometry or typed scalar declaration.", ja: "export の後には geometry または typed scalar declaration が必要です。" },
  "diagnostic.value-if-malformed-condition": { en: "The value-if condition must use the form `if (condition)`.", ja: "value-if の条件は「if (条件)」の形で指定してください。" },
  "diagnostic.value-if-malformed-branch": { en: "A value-if branch must use the form `{ expression }`.", ja: "value-if のbranchは「{ 式 }」の形で指定してください。" },
  "diagnostic.value-match-malformed": { en: "A value-match requires a `{ cases }` body.", ja: "match には「{ ケース }」の本体が必要です。" },
  "diagnostic.value-match-missing-scrutinee": { en: "A value-match requires a scrutinee expression.", ja: "match にはscrutinee式が必要です。" },
  "diagnostic.value-match-missing-closing-brace": { en: "The value-match body is not closed.", ja: "match を閉じる「}」がありません。" },
  "diagnostic.value-match-malformed-arm": { en: "A value-match case must start with a choice option label.", ja: "match ケースはchoice optionラベルで始めてください。" },
  "diagnostic.value-match-missing-arrow": { en: "A value-match case requires `=>`.", ja: "match ケースには「=>」が必要です。" },
  "diagnostic.geometry-array-value-for-invalid": { en: "The geometry-array value-for expression is invalid.", ja: "value-for式が不正です。" },
  "diagnostic.coalesce-missing-left": { en: "The left collection value is missing before `??`.", ja: "?? には左辺の collection 値が必要です。" },
  "diagnostic.coalesce-missing-right": { en: "The right collection value is missing after `??`.", ja: "?? には右辺の collection 値が必要です。" },
  "diagnostic.settings-positional-argument-not-accepted": { en: "The {keyword} statement does not accept a positional argument.", ja: "{keyword}文は位置引数を受け付けません。" },
  "diagnostic.settings-duplicate-positional-argument": { en: "Positional argument '{parameter}' is duplicated in the {keyword} statement.", ja: "{keyword}文の位置引数「{parameter}」が重複しています。" },
  "diagnostic.settings-positional-argument-named": { en: "Positional argument '{parameter}' cannot be supplied by name in the {keyword} statement.", ja: "{keyword}文では位置引数「{parameter}」を名前付き引数として指定できません。" },
  "diagnostic.settings-unknown-argument": { en: "The {keyword} statement has no argument '{argument}'. Candidates: {candidates}.", ja: "{keyword}文に引数「{argument}」はありません。候補: {candidates}。" },
  "diagnostic.settings-duplicate-argument": { en: "Argument '{argument}' is duplicated in the {keyword} statement.", ja: "{keyword}文の引数「{argument}」が重複しています。" },
  "diagnostic.settings-missing-positional-argument": { en: "The required positional argument '{parameter}' is missing from the {keyword} statement.", ja: "{keyword}文には必須の位置引数「{parameter}」が必要です。" },
  "diagnostic.settings-missing-named-argument": { en: "The required argument '{parameter}' is missing from the {keyword} statement.", ja: "{keyword}文には必須引数「{parameter}」が必要です。" },
  "diagnostic.settings-missing-statement-name": { en: "The {keyword} statement requires a name.", ja: "{keyword}には名前が必要です。" },
  "diagnostic.settings-invalid-stop": { en: "The '{token}' syntax is not valid in nui1.", ja: "「{token}」は nui1 の有効な構文ではありません。" },
  "diagnostic.settings-missing-call-open": { en: "The {keyword} statement requires '('.", ja: "{keyword}文には「(」が必要です。" },
  "diagnostic.settings-trailing-token-after-call": { en: "Unexpected token after the {keyword} call.", ja: "{keyword}呼び出しの「)」の後に余分なトークンがあります。" },
  "diagnostic.settings-block-not-allowed": { en: "The {keyword} statement cannot open a block.", ja: "{keyword}文はブロックを開けません。" },
  "diagnostic.settings-layout-block-required": { en: "The layout statement requires a block.", ja: "layout にはブロックが必要です。" },
  "diagnostic.empty-argument": { en: "An argument is empty.", ja: "引数が空です。" },
  "diagnostic.missing-argument-comma": { en: "Arguments must be separated by commas.", ja: "引数はcommaで区切ってください。" },
  "diagnostic.import-top-level-only": { en: "Imports are allowed only at the document top level.", ja: "importは文書のトップレベルにのみ指定できます。" },
  "diagnostic.module-export-top-level-only": { en: "Module exports are allowed only at the module top level.", ja: "Module exportはModuleのトップレベルにのみ指定できます。" },
  "diagnostic.missing-module-instance-equals": { en: "A Module instance requires an initializer.", ja: "Module instanceには初期化式が必要です。" },
  "diagnostic.color-unsupported": { en: "Construction '{construction}' cannot use color because it has no own geometry.", ja: "{construction}は自身の図形を持たないためcolorを指定できません。" },
  "diagnostic.source-rewrite-failed": { en: "The source could not be rewritten safely.", ja: "Sourceを安全に書き換えられません。" },
  "diagnostic.unsafe-rewrite": { en: "The source rewrite is unsafe.", ja: "Sourceの書き換えが安全ではありません。" },
  "diagnostic.unsafe-source-span": { en: "The source span is unsafe.", ja: "Source spanが安全ではありません。" },
  "diagnostic.record-type-not-record": { en: "Type '{name}' is not a record definition.", ja: "型名「{name}」はrecord definitionではありません。" },
  "diagnostic.record-type-forward-reference": { en: "Record type '{name}' is declared later.", ja: "record型「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.record-type-ambiguous": { en: "Record type reference '{name}' is ambiguous.", ja: "record型参照「{name}」が曖昧です。" },
  "diagnostic.record-type-undefined": { en: "Record type '{name}' is undefined.", ja: "record型「{name}」が未定義です。" },
  "diagnostic.record-definition-not-top-level": { en: "Record definitions are allowed only at the document top level.", ja: "record definitionは文書のトップレベルにのみ宣言できます。" },
  "diagnostic.record-parameter-default-unsupported": { en: "Record-typed Module parameters cannot have defaults.", ja: "record型Module parameterにdefaultは指定できません。" },
  "diagnostic.record-reference-invalid": { en: "The record reference is invalid.", ja: "record参照が不正です。" },
  "diagnostic.record-reference-not-record": { en: "Reference '{name}' is not a record value.", ja: "参照先「{name}」はrecord valueではありません。" },
  "diagnostic.record-nominal-type-mismatch": { en: "Record value '{name}' does not match expected record type '{expected}'.", ja: "record value「{name}」は期待されるrecord型「{expected}」と一致しません。" },
  "diagnostic.record-constructor-invalid": { en: "The record value initializer is invalid.", ja: "record valueの初期化式が不正です。" },
  "diagnostic.record-constructor-not-record": { en: "Constructor target '{name}' is not a record.", ja: "constructor対象「{name}」はrecordではありません。" },
  "diagnostic.record-constructor-forward-reference": { en: "Record constructor '{name}' is declared later.", ja: "record constructor「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.record-constructor-ambiguous": { en: "Record constructor reference '{name}' is ambiguous.", ja: "record constructor参照「{name}」が曖昧です。" },
  "diagnostic.record-constructor-undefined": { en: "Record constructor '{name}' is undefined.", ja: "record constructor「{name}」が未定義です。" },
  "diagnostic.record-constructor-invalid-argument": { en: "The record constructor argument is invalid.", ja: "record constructor引数が不正です。" },
  "diagnostic.module-private-member": { en: "Module member '{target}' is not exported.", ja: "Module member「{target}」はexportされていません。" },
  "diagnostic.module-array-outer-capture": { en: "A Module body cannot capture an outer geometry array.", ja: "Module bodyから外側のgeometry arrayをcaptureできません。" },
  "diagnostic.module-undefined-export": { en: "Module export '{target}' is undefined.", ja: "Module export「{target}」が未定義です。" },
  "diagnostic.geometry-array-member-unresolved": { en: "Geometry array member '{member}' could not be resolved.", ja: "geometry array member「{member}」を解決できません。" },
  "diagnostic.geometry-array-member-undefined": { en: "Geometry array member '{member}' could not be resolved.", ja: "geometry array member「{member}」を解決できません。" },
  "diagnostic.geometry-array-reference-forward": { en: "Geometry array '{reference}' is declared later.", ja: "geometry array「{reference}」はこの位置より後で宣言されています。" },
  "diagnostic.geometry-array-reference-ambiguous": { en: "Geometry array reference '{reference}' is ambiguous.", ja: "geometry array参照「{reference}」が曖昧です。" },
  "diagnostic.geometry-array-reference-undefined": { en: "Geometry array reference '{reference}' could not be resolved.", ja: "未解決のgeometry array参照です: {reference}" },
  "diagnostic.geometry-array-member-forward": { en: "Geometry array member '{member}' is declared later.", ja: "geometry array member「{member}」はこの位置より後で宣言されています。" },
  "diagnostic.geometry-array-member-ambiguous": { en: "Geometry array member reference '{member}' is ambiguous.", ja: "geometry array member参照「{member}」が曖昧です。" },
  "diagnostic.geometry-array-member-invalidTraversal": { en: "Geometry array member traversal '{member}' is invalid.", ja: "geometry array member「{member}」のtraversalが不正です。" },
  "diagnostic.geometry-array-reference-invalidTraversal": { en: "Geometry array reference traversal '{reference}' is invalid.", ja: "geometry array参照「{reference}」のtraversalが不正です。" },
  "diagnostic.module-ambiguous-callee": { en: "Module callee '{name}' is ambiguous.", ja: "Module callee「{name}」が曖昧です。" },
  "diagnostic.module-ambiguous-geometry-reference": { en: "Module geometry reference '{name}' is ambiguous.", ja: "Module geometry参照「{name}」が曖昧です。" },
  "diagnostic.module-ambiguous-instance-reference": { en: "Module instance reference '{name}' is ambiguous.", ja: "Module instance参照「{name}」が曖昧です。" },
  "diagnostic.module-ambiguous-reference": { en: "Module scalar reference '{name}' is ambiguous.", ja: "Module scalar参照「{name}」が曖昧です。" },
  "diagnostic.module-callee-not-definition": { en: "'{name}' is not a Module definition.", ja: "「{name}」はModule definitionではありません。" },
  "diagnostic.module-default-invalid-reference": { en: "Module default reference '{name}' is not a scalar binding.", ja: "Module defaultの参照先「{name}」はscalar bindingではありません。" },
  "diagnostic.module-default-parameter-order": { en: "Module defaults may reference only earlier parameters; '{name}' is later.", ja: "Module defaultでは先に宣言されたparameterのみ参照できます。「{name}」は後のparameterです。" },
  "diagnostic.module-document-binding-unavailable": { en: "Document scalar binding '{name}' is unavailable in this Module.", ja: "このModuleではdocument scalar「{name}」のbindingを利用できません。" },
  "diagnostic.module-duplicate-argument": { en: "Module argument '{argument}' is duplicated.", ja: "Module引数「{argument}」が重複しています。" },
  "diagnostic.module-duplicate-function-argument": { en: "The Module function argument is duplicated.", ja: "Module関数引数が重複しています。" },
  "diagnostic.module-forward-callee": { en: "Module callee '{name}' is declared later.", ja: "Module callee「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-forward-geometry-reference": { en: "Geometry '{name}' is declared later.", ja: "geometry「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-forward-instance-reference": { en: "Module instance '{name}' is declared later.", ja: "module instance「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-forward-reference": { en: "Module scalar '{name}' is declared later.", ja: "module scalar「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-function-arity-mismatch": { en: "The Module function argument count is incorrect.", ja: "Module関数の引数の数が不正です。" },
  "diagnostic.module-function-call-style-mismatch": { en: "The Module function call style is unsupported.", ja: "Module関数の呼び出し形式が不正です。" },
  "diagnostic.module-geometry-default": { en: "Geometry Module parameter '{name}' cannot have a default.", ja: "geometry Module parameter「{name}」にはdefaultを指定できません。" },
  "diagnostic.module-geometry-property-reference": { en: "The Module geometry property reference is invalid.", ja: "Module geometry property参照が不正です。" },
  "diagnostic.module-geometry-property-type-mismatch": { en: "Module geometry property reference '{target}' has the wrong type.", ja: "Module geometry property参照「{target}」の型が一致しません。" },
  "diagnostic.module-geometry-reference-in-default": { en: "Geometry '{name}' is not allowed in a Module default.", ja: "Module defaultではgeometry「{name}」を参照できません。" },
  "diagnostic.module-geometry-reference-in-scalar": { en: "Geometry '{name}' is not allowed in a scalar expression.", ja: "scalar expressionではgeometry「{name}」を参照できません。" },
  "diagnostic.module-invalid-choice-literal": { en: "The Module choice value is invalid.", ja: "Module choice値が不正です。" },
  "diagnostic.module-invalid-reference": { en: "Module reference '{name}' is invalid.", ja: "Module参照「{name}」が不正です。" },
  "diagnostic.module-missing-argument": { en: "Required Module argument '{parameter}' is missing.", ja: "必須のModule引数「{parameter}」がありません。" },
  "diagnostic.module-missing-function-argument": { en: "A required Module function argument is missing.", ja: "必須のModule関数引数がありません。" },
  "diagnostic.module-outer-capture": { en: "A Module body cannot capture outer value '{name}'.", ja: "Module bodyから外側の値「{name}」をcaptureできません。" },
  "diagnostic.module-parameter-collision": { en: "Module parameter '{name}' collides with another name.", ja: "Module parameter「{name}」の名前が衝突しています。" },
  "diagnostic.module-parameter-duplicate": { en: "Module parameter '{parameter}' is duplicated.", ja: "Module parameter「{parameter}」が重複しています。" },
  "diagnostic.module-record-ambiguous-reference": { en: "Module record reference '{name}' is ambiguous.", ja: "Module record参照「{name}」が曖昧です。" },
  "diagnostic.module-record-field-unknown": { en: "Record '{record}' has no field '{field}'.", ja: "record「{record}」にfield「{field}」はありません。" },
  "diagnostic.module-record-forward-reference": { en: "Module record value '{name}' is declared later.", ja: "Module record value「{name}」はこの位置より後で宣言されています。" },
  "diagnostic.module-record-invalid-reference": { en: "Module record value '{name}' is not a namespace.", ja: "Module record value「{name}」はnamespaceではありません。" },
  "diagnostic.module-record-reference-invalid": { en: "The Module record reference is invalid.", ja: "Module record参照が不正です。" },
  "diagnostic.module-record-value-in-geometry": { en: "Record value '{name}' cannot be used as geometry.", ja: "record value「{name}」をgeometryとして使用できません。" },
  "diagnostic.module-record-value-in-scalar": { en: "Record value '{name}' cannot be used as a scalar.", ja: "record value「{name}」をscalarとして使用できません。" },
  "diagnostic.module-resolved-callee": { en: "The Module callee resolved unexpectedly.", ja: "Module calleeの解決結果が不正です。" },
  "diagnostic.module-scalar-geometry-reference": { en: "Scalar expressions cannot reference geometry '{name}'.", ja: "scalar expressionからgeometry「{name}」を参照できません。" },
  "diagnostic.module-scalar-type-mismatch": { en: "The Module scalar type does not match.", ja: "Module scalarの型が一致しません。" },
  "diagnostic.module-undefined-instance-reference": { en: "Module instance '{name}' is undefined.", ja: "module instance「{name}」が未定義です。" },
  "diagnostic.module-undefined-geometry-reference": { en: "Geometry '{name}' is undefined.", ja: "geometry「{name}」が未定義です。" },
  "diagnostic.module-undefined-reference": { en: "Module scalar '{name}' is undefined.", ja: "module scalar「{name}」が未定義です。" },
  "diagnostic.module-unknown-argument": { en: "Module '{module}' has no argument '{argument}'.", ja: "module「{module}」にargument「{argument}」はありません。" },
  "diagnostic.module-unknown-function": { en: "The Module function is unknown.", ja: "Module関数が不明です。" },
  "diagnostic.module-unknown-function-argument": { en: "The Module function argument is unknown.", ja: "Module関数引数が不明です。" },
  "diagnostic.module-unknown-geometry-property": { en: "Geometry property '{property}' is unknown.", ja: "geometry property「{property}」が不明です。" },
  "diagnostic.module-unresolved-callee": { en: "Module '{name}' could not be resolved.", ja: "Module「{name}」を解決できません。" },
  "diagnostic.module-unterminated-string": { en: "The Module string is not closed.", ja: "Moduleの文字列が閉じられていません。" },
  "diagnostic.module-physical-newline-in-string": { en: "A Module string cannot contain a physical newline.", ja: "Moduleの文字列に改行を含めることはできません。" },
  "diagnostic.module-invalid-string-escape": { en: "The Module string escape is invalid.", ja: "Moduleの文字列escapeが不正です。" },
  "diagnostic.module-interpolation-nested-not-supported": { en: "Nested Module interpolation is not supported.", ja: "Module interpolationの入れ子はサポートされていません。" },
  "diagnostic.module-interpolation-empty": { en: "The Module interpolation is empty.", ja: "Module interpolationが空です。" },
  "diagnostic.module-unterminated-interpolation": { en: "The Module interpolation is not closed.", ja: "Module interpolationが閉じられていません。" },
  "diagnostic.related.declaration": { en: "Related declaration", ja: "関連する宣言" },
  "diagnostic.related.parameter-declaration": { en: "Related parameter declaration", ja: "関連するparameter宣言" },
  "diagnostic.related.expected-parameter-type": { en: "Expected parameter type", ja: "期待されるparameter型" },
  "diagnostic.related.first-parameter": { en: "First parameter with this name", ja: "この名前の最初のparameter" },
  "diagnostic.related.iteration-declaration": { en: "Related iteration declaration", ja: "関連するiteration宣言" },
  "diagnostic.related.module-member-declaration": { en: "Related Module member declaration", ja: "関連するModule member宣言" },
  "diagnostic.related.geometry-declaration": { en: "Related geometry declaration", ja: "関連するgeometry宣言" },
  "diagnostic.related.record-value": { en: "Related record value", ja: "関連するrecord value" },
  "diagnostic.related.module-recursion": { en: "Related call in the Module recursion cycle", ja: "Module recursion cycleに含まれる関連call" },
  "diagnostic.related.first-argument": { en: "First argument with this name", ja: "この名前の最初のargument" },
  "diagnostic.related.called-module-definition": { en: "Called Module definition", ja: "呼び出されたModule定義" }
} satisfies TranslationCatalog;

export type DiagnosticPresentation = DslDiagnosticPresentation;
export type DiagnosticLocalizationKey = keyof typeof diagnosticTranslationCatalog;

const translatePresentation = (
  presentation: DiagnosticPresentation,
  displayLanguage: string
): string | null => {
  const translated = createTranslator(diagnosticTranslationCatalog, resolveLocale(displayLanguage))(
    presentation.key,
    presentation.parameters
  );
  return translated === presentation.key ? null : translated;
};

export const diagnosticTextFor = (
  diagnostic: Pick<CompilerDiagnostic, "message" | "presentation">,
  displayLanguage: string
): string => diagnostic.presentation
  ? translatePresentation(diagnostic.presentation, displayLanguage) ?? diagnostic.message
  : diagnostic.message;

export const diagnosticRelatedTextFor = (
  related: Pick<CompilerDiagnosticRelatedInformation, "message" | "presentation">,
  displayLanguage: string
): string => related.presentation
  ? translatePresentation(related.presentation, displayLanguage) ?? related.message
  : related.message;

export const diagnosticSuffixTextFor = (
  presentation: DiagnosticPresentation | undefined,
  displayLanguage: string
): string | null => presentation ? translatePresentation(presentation, displayLanguage) : null;

export const diagnosticMessageFor = (
  diagnostic: Pick<CompilerDiagnostic, "message" | "presentation" | "suffixPresentation">,
  displayLanguage: string
): string => [
  diagnosticTextFor(diagnostic, displayLanguage),
  diagnosticSuffixTextFor(diagnostic.suffixPresentation, displayLanguage)
].filter((part): part is string => part !== null).join(" ");
