import {
  ALargeSmall,
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Badge,
  Bookmark,
  BoxSelect,
  Braces,
  Check,
  CheckCheck,
  Circle,
  CircleCheck,
  CircleDot,
  CircleX,
  Clipboard,
  ClipboardCopy,
  Columns3,
  Combine,
  Compass,
  Component,
  Copy,
  CornerDownRight,
  CornerUpRight,
  Crosshair,
  Diameter,
  Dot,
  Download,
  DraftingCompass,
  Edit3,
  Eye,
  EyeOff,
  File,
  FileDown,
  FilePlus,
  Flag,
  FlipHorizontal,
  FlipVertical,
  Focus,
  FolderOpen,
  GitBranch,
  Grab,
  Grid2X2,
  Grid3X3,
  GripVertical,
  Hand,
  Hash,
  Image,
  Images,
  Info,
  Layers,
  Link,
  ListTree,
  LocateFixed,
  Lock,
  Magnet,
  MapPin,
  Maximize,
  Merge,
  Minimize,
  Minus,
  MousePointer2,
  MousePointerClick,
  Move,
  MoveDownRight,
  MoveHorizontal,
  MoveRight,
  MoveUpRight,
  MoveVertical,
  PanelLeft,
  PanelRight,
  Parentheses,
  PenLine,
  Pencil,
  Percent,
  Pin,
  Plus,
  Printer,
  Radius,
  Ratio,
  Redo2,
  RefreshCcw,
  RotateCcw,
  RotateCw,
  Route,
  Rows3,
  Ruler,
  Save,
  SaveAll,
  Scan,
  ScanLine,
  ScanSearch,
  Scissors,
  Search,
  Settings,
  Shapes,
  Sigma,
  Slash,
  SlidersHorizontal,
  Split,
  Spline,
  Square,
  SquareCheck,
  Star,
  Table2,
  Tag,
  Target,
  Text,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TriangleAlert,
  Type,
  Undo2,
  Unlink,
  Unlock,
  Upload,
  Variable,
  Waypoints,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon
} from "lucide-react";

export type CommandRibbonIconCategory =
  | "drafting"
  | "edit"
  | "selection"
  | "view"
  | "file"
  | "layout"
  | "logic"
  | "mark";

export type CommandRibbonIconDefinition = {
  id: string;
  label: string;
  category: CommandRibbonIconCategory;
  keywords: readonly string[];
  icon: LucideIcon;
};

export const commandRibbonIconCategoryLabels: Record<CommandRibbonIconCategory, string> = {
  drafting: "作図",
  edit: "編集",
  selection: "選択",
  view: "表示",
  file: "ファイル",
  layout: "配置",
  logic: "式/制御",
  mark: "目印"
};

export const commandRibbonIconCatalog = [
  { id: "circle-dot", label: "点", category: "drafting", keywords: ["point", "anchor"], icon: CircleDot },
  { id: "circle", label: "円", category: "drafting", keywords: ["circle", "round"], icon: Circle },
  { id: "dot", label: "小点", category: "drafting", keywords: ["dot", "node"], icon: Dot },
  { id: "crosshair", label: "十字", category: "drafting", keywords: ["crosshair", "center"], icon: Crosshair },
  { id: "locate-fixed", label: "固定点", category: "drafting", keywords: ["locate", "fixed"], icon: LocateFixed },
  { id: "map-pin", label: "ピン点", category: "drafting", keywords: ["pin", "point"], icon: MapPin },
  { id: "slash", label: "線", category: "drafting", keywords: ["line", "slash"], icon: Slash },
  { id: "minus", label: "水平線", category: "drafting", keywords: ["line", "minus"], icon: Minus },
  { id: "spline", label: "曲線", category: "drafting", keywords: ["curve", "bezier", "spline"], icon: Spline },
  { id: "corner-down-right", label: "角下", category: "drafting", keywords: ["corner", "arc"], icon: CornerDownRight },
  { id: "corner-up-right", label: "角上", category: "drafting", keywords: ["corner", "arc"], icon: CornerUpRight },
  { id: "waypoints", label: "経路", category: "drafting", keywords: ["path", "route"], icon: Waypoints },
  { id: "route", label: "ルート", category: "drafting", keywords: ["path", "route"], icon: Route },
  { id: "git-branch", label: "分岐線", category: "drafting", keywords: ["branch", "path"], icon: GitBranch },
  { id: "ruler", label: "定規", category: "drafting", keywords: ["measure", "length"], icon: Ruler },
  { id: "drafting-compass", label: "コンパス", category: "drafting", keywords: ["draft", "compass"], icon: DraftingCompass },
  { id: "compass", label: "方位", category: "drafting", keywords: ["compass", "angle"], icon: Compass },
  { id: "diameter", label: "直径", category: "drafting", keywords: ["diameter", "circle"], icon: Diameter },
  { id: "radius", label: "半径", category: "drafting", keywords: ["radius", "arc"], icon: Radius },
  { id: "ratio", label: "比率", category: "drafting", keywords: ["ratio", "scale"], icon: Ratio },

  { id: "plus", label: "追加", category: "edit", keywords: ["add", "new"], icon: Plus },
  { id: "x", label: "閉じる", category: "edit", keywords: ["close", "cancel"], icon: X },
  { id: "check", label: "確定", category: "edit", keywords: ["check", "ok"], icon: Check },
  { id: "check-check", label: "一括確定", category: "edit", keywords: ["check", "all"], icon: CheckCheck },
  { id: "pen-line", label: "ペン", category: "edit", keywords: ["pen", "draw"], icon: PenLine },
  { id: "pencil", label: "鉛筆", category: "edit", keywords: ["pencil", "edit"], icon: Pencil },
  { id: "edit-3", label: "編集", category: "edit", keywords: ["edit", "modify"], icon: Edit3 },
  { id: "copy", label: "コピー", category: "edit", keywords: ["copy", "duplicate"], icon: Copy },
  { id: "clipboard", label: "貼付", category: "edit", keywords: ["clipboard", "paste"], icon: Clipboard },
  { id: "clipboard-copy", label: "複写", category: "edit", keywords: ["clipboard", "copy"], icon: ClipboardCopy },
  { id: "trash", label: "削除", category: "edit", keywords: ["delete", "trash"], icon: Trash2 },
  { id: "scissors", label: "切断", category: "edit", keywords: ["cut", "split"], icon: Scissors },
  { id: "split", label: "分割", category: "edit", keywords: ["split", "divide"], icon: Split },
  { id: "combine", label: "結合", category: "edit", keywords: ["combine", "join"], icon: Combine },
  { id: "merge", label: "マージ", category: "edit", keywords: ["merge", "join"], icon: Merge },
  { id: "undo-2", label: "戻す", category: "edit", keywords: ["undo"], icon: Undo2 },
  { id: "redo-2", label: "やり直し", category: "edit", keywords: ["redo"], icon: Redo2 },
  { id: "rotate-ccw", label: "左回転", category: "edit", keywords: ["rotate", "undo"], icon: RotateCcw },
  { id: "rotate-cw", label: "右回転", category: "edit", keywords: ["rotate"], icon: RotateCw },
  { id: "refresh-ccw", label: "更新", category: "edit", keywords: ["refresh", "reload"], icon: RefreshCcw },
  { id: "flip-horizontal", label: "左右反転", category: "edit", keywords: ["mirror", "flip"], icon: FlipHorizontal },
  { id: "flip-vertical", label: "上下反転", category: "edit", keywords: ["mirror", "flip"], icon: FlipVertical },
  { id: "move", label: "移動", category: "edit", keywords: ["move"], icon: Move },
  { id: "move-right", label: "右移動", category: "edit", keywords: ["move", "offset"], icon: MoveRight },
  { id: "move-up-right", label: "斜め上", category: "edit", keywords: ["move", "offset"], icon: MoveUpRight },
  { id: "move-down-right", label: "斜め下", category: "edit", keywords: ["move", "offset"], icon: MoveDownRight },
  { id: "move-horizontal", label: "横移動", category: "edit", keywords: ["move", "horizontal"], icon: MoveHorizontal },
  { id: "move-vertical", label: "縦移動", category: "edit", keywords: ["move", "vertical"], icon: MoveVertical },
  { id: "arrow-right", label: "右矢印", category: "edit", keywords: ["arrow", "next"], icon: ArrowRight },
  { id: "arrow-left", label: "左矢印", category: "edit", keywords: ["arrow", "previous"], icon: ArrowLeft },
  { id: "arrow-up", label: "上矢印", category: "edit", keywords: ["arrow", "up"], icon: ArrowUp },
  { id: "arrow-down", label: "下矢印", category: "edit", keywords: ["arrow", "down"], icon: ArrowDown },

  { id: "mouse-pointer-2", label: "選択", category: "selection", keywords: ["select", "cursor"], icon: MousePointer2 },
  { id: "mouse-pointer-click", label: "クリック", category: "selection", keywords: ["click", "select"], icon: MousePointerClick },
  { id: "hand", label: "手", category: "selection", keywords: ["hand", "pan"], icon: Hand },
  { id: "grab", label: "掴む", category: "selection", keywords: ["grab", "drag"], icon: Grab },
  { id: "box-select", label: "範囲選択", category: "selection", keywords: ["box", "select"], icon: BoxSelect },
  { id: "scan", label: "スキャン", category: "selection", keywords: ["scan", "pick"], icon: Scan },
  { id: "scan-line", label: "線選択", category: "selection", keywords: ["scan", "line"], icon: ScanLine },
  { id: "scan-search", label: "検索選択", category: "selection", keywords: ["scan", "search"], icon: ScanSearch },
  { id: "focus", label: "フォーカス", category: "selection", keywords: ["focus", "target"], icon: Focus },
  { id: "target", label: "ターゲット", category: "selection", keywords: ["target", "aim"], icon: Target },

  { id: "zoom-in", label: "拡大", category: "view", keywords: ["zoom", "in"], icon: ZoomIn },
  { id: "zoom-out", label: "縮小", category: "view", keywords: ["zoom", "out"], icon: ZoomOut },
  { id: "search", label: "検索", category: "view", keywords: ["search", "find"], icon: Search },
  { id: "eye", label: "表示", category: "view", keywords: ["visible", "show"], icon: Eye },
  { id: "eye-off", label: "非表示", category: "view", keywords: ["hidden", "hide"], icon: EyeOff },
  { id: "layers", label: "レイヤー", category: "view", keywords: ["layer"], icon: Layers },
  { id: "list-tree", label: "ツリー", category: "view", keywords: ["tree", "list"], icon: ListTree },
  { id: "panel-left", label: "左パネル", category: "view", keywords: ["panel", "left"], icon: PanelLeft },
  { id: "panel-right", label: "右パネル", category: "view", keywords: ["panel", "right"], icon: PanelRight },
  { id: "settings", label: "設定", category: "view", keywords: ["settings"], icon: Settings },
  { id: "sliders-horizontal", label: "調整", category: "view", keywords: ["slider", "adjust"], icon: SlidersHorizontal },
  { id: "toggle-left", label: "オフ", category: "view", keywords: ["toggle", "off"], icon: ToggleLeft },
  { id: "toggle-right", label: "オン", category: "view", keywords: ["toggle", "on"], icon: ToggleRight },
  { id: "maximize", label: "最大化", category: "view", keywords: ["maximize", "fit"], icon: Maximize },
  { id: "minimize", label: "最小化", category: "view", keywords: ["minimize"], icon: Minimize },

  { id: "save", label: "保存", category: "file", keywords: ["save", "file"], icon: Save },
  { id: "save-all", label: "全保存", category: "file", keywords: ["save", "all"], icon: SaveAll },
  { id: "folder-open", label: "開く", category: "file", keywords: ["open", "folder"], icon: FolderOpen },
  { id: "file", label: "ファイル", category: "file", keywords: ["file"], icon: File },
  { id: "file-plus", label: "新規", category: "file", keywords: ["new", "file"], icon: FilePlus },
  { id: "file-down", label: "書出", category: "file", keywords: ["export", "download"], icon: FileDown },
  { id: "upload", label: "読込", category: "file", keywords: ["import", "upload"], icon: Upload },
  { id: "download", label: "DL", category: "file", keywords: ["download"], icon: Download },
  { id: "printer", label: "印刷", category: "file", keywords: ["print"], icon: Printer },
  { id: "image", label: "画像", category: "file", keywords: ["image"], icon: Image },
  { id: "images", label: "画像群", category: "file", keywords: ["images"], icon: Images },

  { id: "square", label: "四角", category: "layout", keywords: ["square", "box"], icon: Square },
  { id: "square-check", label: "チェック枠", category: "layout", keywords: ["square", "check"], icon: SquareCheck },
  { id: "grid-2x2", label: "グリッド2", category: "layout", keywords: ["grid"], icon: Grid2X2 },
  { id: "grid-3x3", label: "グリッド3", category: "layout", keywords: ["grid"], icon: Grid3X3 },
  { id: "table-2", label: "表", category: "layout", keywords: ["table"], icon: Table2 },
  { id: "rows-3", label: "行", category: "layout", keywords: ["row"], icon: Rows3 },
  { id: "columns-3", label: "列", category: "layout", keywords: ["column"], icon: Columns3 },
  { id: "component", label: "部品", category: "layout", keywords: ["component"], icon: Component },
  { id: "shapes", label: "図形", category: "layout", keywords: ["shape"], icon: Shapes },
  { id: "align-left", label: "左揃え", category: "layout", keywords: ["align"], icon: AlignLeft },
  { id: "align-center", label: "中央揃え", category: "layout", keywords: ["align"], icon: AlignCenter },
  { id: "align-right", label: "右揃え", category: "layout", keywords: ["align"], icon: AlignRight },

  { id: "sigma", label: "合計", category: "logic", keywords: ["sum", "formula"], icon: Sigma },
  { id: "variable", label: "変数", category: "logic", keywords: ["variable"], icon: Variable },
  { id: "braces", label: "波括弧", category: "logic", keywords: ["braces", "code"], icon: Braces },
  { id: "parentheses", label: "括弧", category: "logic", keywords: ["parentheses"], icon: Parentheses },
  { id: "percent", label: "割合", category: "logic", keywords: ["percent"], icon: Percent },
  { id: "hash", label: "番号", category: "logic", keywords: ["hash", "number"], icon: Hash },
  { id: "text", label: "文字", category: "logic", keywords: ["text", "label"], icon: Text },
  { id: "type", label: "タイプ", category: "logic", keywords: ["type", "font"], icon: Type },
  { id: "a-large-small", label: "大小文字", category: "logic", keywords: ["font", "text"], icon: ALargeSmall },

  { id: "tag", label: "タグ", category: "mark", keywords: ["tag", "label"], icon: Tag },
  { id: "badge", label: "バッジ", category: "mark", keywords: ["badge"], icon: Badge },
  { id: "bookmark", label: "しおり", category: "mark", keywords: ["bookmark"], icon: Bookmark },
  { id: "star", label: "星", category: "mark", keywords: ["star", "favorite"], icon: Star },
  { id: "flag", label: "旗", category: "mark", keywords: ["flag", "mark"], icon: Flag },
  { id: "pin", label: "留める", category: "mark", keywords: ["pin"], icon: Pin },
  { id: "link", label: "リンク", category: "mark", keywords: ["link"], icon: Link },
  { id: "unlink", label: "解除", category: "mark", keywords: ["unlink"], icon: Unlink },
  { id: "lock", label: "ロック", category: "mark", keywords: ["lock"], icon: Lock },
  { id: "unlock", label: "解除鍵", category: "mark", keywords: ["unlock"], icon: Unlock },
  { id: "magnet", label: "吸着", category: "mark", keywords: ["snap", "magnet"], icon: Magnet },
  { id: "circle-check", label: "完了", category: "mark", keywords: ["done", "ok"], icon: CircleCheck },
  { id: "circle-x", label: "中止", category: "mark", keywords: ["cancel", "error"], icon: CircleX },
  { id: "triangle-alert", label: "警告", category: "mark", keywords: ["warning", "alert"], icon: TriangleAlert },
  { id: "info", label: "情報", category: "mark", keywords: ["info"], icon: Info }
] as const satisfies readonly CommandRibbonIconDefinition[];

export type CommandRibbonIconId = (typeof commandRibbonIconCatalog)[number]["id"];

export const commandRibbonIconIds = commandRibbonIconCatalog.map(
  (definition) => definition.id
) as CommandRibbonIconId[];

export const commandRibbonIconLabels = Object.fromEntries(
  commandRibbonIconCatalog.map((definition) => [definition.id, definition.label])
) as Record<CommandRibbonIconId, string>;

export const commandRibbonIconComponents = Object.fromEntries(
  commandRibbonIconCatalog.map((definition) => [definition.id, definition.icon])
) as Record<CommandRibbonIconId, LucideIcon>;

export const CommandRibbonGripIcon = GripVertical;

export const isCommandRibbonIconId = (value: unknown): value is CommandRibbonIconId =>
  typeof value === "string" && (commandRibbonIconIds as readonly string[]).includes(value);
