import type { CadElementType } from "../../types/geometry";

export type Nui3CanonicalElementStatement = {
  key: string;
  elementType: CadElementType;
  construction: string;
  minimal: string;
  populated: string;
};

/** Static P5 logical output; C1/P9 may use these literals without serializing. */
export const nui3CanonicalElementStatements: readonly Nui3CanonicalElementStatement[] = [
  { key: "freePoint", elementType: "freePoint", construction: "coordinate", minimal: "point freePoint-default-min = coordinate(x: 0, y: 0)", populated: "point populated = coordinate(x: 12, y: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "offsetPoint", elementType: "offsetPoint", construction: "offset", minimal: "point offsetPoint-default-min = offset(from: A, dx: 0, dy: 0)", populated: "point populated = offset(from: A, dx: 12, dy: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "polarOffsetPoint", elementType: "polarOffsetPoint", construction: "polar", minimal: "point polarOffsetPoint-default-min = polar(from: A, angle: 0, distance: 0)", populated: "point populated = polar(from: A, angle: 12, distance: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "divisionPoint", elementType: "divisionPoint", construction: "between", minimal: "point divisionPoint-default-min = between(start: A, end: B, ratio: 0.5, steps: [ratio: 0.01])", populated: "point populated = between(start: A, end: A, ratio: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "lineDivisionPoint", elementType: "lineDivisionPoint", construction: "onLine", minimal: "point lineDivisionPoint-default-min = onLine(from: AB.start, ratio: 0.5, steps: [ratio: 0.01])", populated: "point populated = onLine(from: AB.end, ratio: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "intersectionPoint", elementType: "intersectionPoint", construction: "intersection", minimal: "point intersectionPoint-default-min = intersection(line1: AB, line2: CD, index: 0, extensions: true)", populated: "point populated = intersection(line1: AB, line2: AB, index: 12, extensions: true, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "lineTangentOffsetPoint", elementType: "lineTangentOffsetPoint", construction: "tangentOffset", minimal: "point lineTangentOffsetPoint-default-min = tangentOffset(line: AB, base: AB.start, angle: 0, distance: 0)", populated: "point populated = tangentOffset(line: AB, base: A, angle: 12, distance: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "line", elementType: "line", construction: "segment", minimal: "line line-default-min = segment(start: A, end: B)", populated: "line populated = segment(start: A, end: A, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "angleLengthLine", elementType: "angleLengthLine", construction: "polar", minimal: "line angleLengthLine-default-min = polar(start: A, angle: 0, length: 100)", populated: "line populated = polar(start: A, angle: 12, length: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "offsetLine", elementType: "offsetLine", construction: "offset", minimal: "line offsetLine-default-min = offset(sources: [AB], distance: 10, side: right, closed: false, suppressTrimWarnings: false)", populated: "line populated = offset(sources: [AB, CD], distance: 12, side: left, closed: true, suppressTrimWarnings: true, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "splitLine", elementType: "splitLine", construction: "split", minimal: "line splitLine-default-min = split(source: AB, at: A)", populated: "line populated = split(source: AB, at: A, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "copyLine", elementType: "copyLine", construction: "copy", minimal: "line copyLine-default-min = copy(startPoint: A, endPoint: B, scale: 1, angleDeg: 0, mirrorX: false, baseLines: [AB])", populated: "line populated = copy(startPoint: A, endPoint: A, scale: 12, angleDeg: 12, mirrorX: true, baseLines: [AB, CD], color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "symmetricCopyLine", elementType: "symmetricCopyLine", construction: "mirrorCopy", minimal: "line symmetricCopyLine-default-min = mirrorCopy(axis1: A, axis2: B, baseLines: [AB])", populated: "line populated = mirrorCopy(axis1: A, axis2: A, baseLines: [AB, CD], color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "edge", elementType: "edge", construction: "edge", minimal: "edge(end1: AB.start, end2: CD.start, index: 0)", populated: "edge(end1: AB.end, end2: AB.end, index: 12, steps: [x: 0.5], vars: [width: 8])" },
  { key: "extendTrim", elementType: "extendTrim", construction: "extend", minimal: "extend(end: AB.start, to: A)", populated: "extend(end: AB.end, to: A, steps: [x: 0.5], vars: [width: 8])" },
  { key: "move", elementType: "move", construction: "move", minimal: "move(targets: [AB], from: A, to: B, scale: 1, angleDeg: 0, mirrorX: false)", populated: "move(targets: [AB, CD], from: A, to: A, scale: 12, angleDeg: 12, mirrorX: true, steps: [x: 0.5], vars: [width: 8])" },
  { key: "symmetricMove", elementType: "symmetricMove", construction: "mirrorMove", minimal: "mirrorMove(targets: [AB], axis1: A, axis2: B)", populated: "mirrorMove(targets: [AB, CD], axis1: A, axis2: A, steps: [x: 0.5], vars: [width: 8])" },
  { key: "pathReverse", elementType: "pathReverse", construction: "reverse", minimal: "reverse(target: AB)", populated: "reverse(target: AB, state: disabled)" },
  { key: "bezierCurve", elementType: "bezierCurve", construction: "bezier", minimal: "curve bezierCurve-default-min = bezier(start: A, end: B, startAngle: 0, startLength: 30, endAngle: 0, endLength: 30)", populated: "curve populated = bezier(start: A, end: A, startAngle: 12, startLength: 12, endAngle: 12, endLength: 12, intermediates: [C:45:20:25], color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "arcLine", elementType: "arcLine", construction: "arc", minimal: "arc arcLine-default-min = arc(center: A, radius: 30, start: 0, end: 90)", populated: "arc populated = arc(center: A, radius: 12, start: 12, end: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "threePointArcLine", elementType: "threePointArcLine", construction: "through", minimal: "arc threePointArcLine-default-min = through(point1: A, point2: B, point3: C, start: 0, end: 90)", populated: "arc populated = through(point1: A, point2: A, point3: A, start: 12, end: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "cornerRadiusArcLine", elementType: "cornerRadiusArcLine", construction: "corner", minimal: "arc cornerRadiusArcLine-default-min = corner(end1: AB.start, end2: CD.start, radius: 10, index: 0)", populated: "arc populated = corner(end1: AB.end, end2: AB.end, radius: 12, index: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "text", elementType: "text", construction: "label", minimal: "text text-default-min = label(text: \"テキスト\", anchor: none, size: 3)", populated: "text populated = label(text: \"populated\", anchor: A, size: 12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "image", elementType: "image", construction: "image", minimal: "image image-default-min = image(source: \"\", origin: (0, 0), naturalWidthPx: 1, naturalHeightPx: 1, sourceDpi: 300, targetPixelsPerMm: 11.811023622047244, scale: 1, angleDeg: 0, mirrorX: false, steps: [scale: 0.01])", populated: "image populated = image(source: \"populated\", origin: A, naturalWidthPx: 12, naturalHeightPx: 12, sourceDpi: 12, targetPixelsPerMm: 12, scale: 12, angleDeg: 12, mirrorX: true, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "group", elementType: "group", construction: "", minimal: "group group-default-min", populated: "group populated (printEnabled: true, printAnchor: A, roles: [seam], color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "conditionalGroup", elementType: "conditionalGroup", construction: "", minimal: "if conditionalGroup-default-min (1)", populated: "if populated (12, color: red, steps: [x: 0.5], vars: [width: 8])" },
  { key: "forGroup", elementType: "forGroup", construction: "", minimal: "for forGroup-default-min (i, from: 0, count: 3, step: 1, showGenerated: false)", populated: "for populated (populated, from: 12, count: 12, step: 12, showGenerated: true, color: red, steps: [x: 0.5], vars: [width: 8])" },
] as const;
